import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Get all active promo planner clients
    const { data: clients, error: clientsError } = await supabase
      .from("promo_planner_clients")
      .select("*")
      .eq("active", true);

    if (clientsError) {
      throw new Error(`Failed to query clients: ${clientsError.message}`);
    }

    if (!clients || clients.length === 0) {
      return new Response(JSON.stringify({ message: "No active promo planner clients" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Calculate next month
    const now = new Date();
    const nextMonth = new Date(now.getFullYear(), now.getMonth() + 1, 1);
    const monthName = nextMonth.toLocaleString("en-US", { month: "long", year: "numeric" });

    let sent = 0;
    let errors = 0;

    for (const client of clients) {
      try {
        // Generate promo calendar with Claude
        const aiRes = await fetch("https://api.anthropic.com/v1/messages", {
          method: "POST",
          headers: {
            "x-api-key": Deno.env.get("ANTHROPIC_API_KEY")!,
            "content-type": "application/json",
            "anthropic-version": "2023-06-01",
          },
          body: JSON.stringify({
            model: "claude-haiku-4-5-20251001",
            max_tokens: 800,
            messages: [
              {
                role: "user",
                content: `Create a promotional calendar for ${monthName} for "${client.business_name}" in the ${client.industry || "local service"} industry. Include 4 weekly promotions tied to seasons, holidays, or industry trends. For each week provide:
1. Promo Name
2. Dates (week of)
3. Discount/Offer details
4. Suggested social media copy (1-2 sentences)
5. Suggested email subject line

Format as an HTML table with clean styling. Use colors #e8621a for headers and #1e293b for text. Keep it concise and actionable.`,
              },
            ],
          }),
        });

        if (!aiRes.ok) {
          console.error("Claude API error:", await aiRes.text());
          errors++;
          continue;
        }

        const aiData = await aiRes.json();
        const calendarHtml = aiData.content[0].text;

        // Email the calendar
        const emailRes = await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${Deno.env.get("RESEND_API_KEY")}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            from: "Matt Michels <matt@notify.m2training.com>",
            to: [client.client_email],
            subject: `📅 Your ${monthName} Promo Calendar — ${client.business_name}`,
            html: `
              <div style="font-family:sans-serif;max-width:700px;margin:0 auto;">
                <h1 style="color:#e8621a;margin-bottom:4px;">${monthName} Promotional Calendar</h1>
                <p style="color:#64748b;margin-top:0;">Prepared for ${client.business_name}</p>
                ${calendarHtml}
                <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
                <p style="color:#64748b;font-size:13px;">This calendar was generated by M² Performance Training AI. Customize any promotion to fit your brand. Questions? Reply to this email.</p>
              </div>
            `,
          }),
        });

        if (!emailRes.ok) {
          console.error("Resend email failed:", await emailRes.text());
          errors++;
          continue;
        }

        // Update plan_count and last_sent_at
        await supabase
          .from("promo_planner_clients")
          .update({
            plan_count: (client.plan_count || 0) + 1,
            last_sent_at: new Date().toISOString(),
          })
          .eq("id", client.id);

        sent++;
      } catch (innerErr) {
        console.error(`Error processing client ${client.id}:`, innerErr);
        errors++;
      }
    }

    return new Response(
      JSON.stringify({ success: true, sent, errors, total: clients.length }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    console.error("promo-planner-generator error:", err);
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
