import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SUPABASE_SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY") || "";
const GOOGLE_MAPS_API_KEY = Deno.env.get("GOOGLE_MAPS_API_KEY") || "";
const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") || "";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface CompetitorData {
  name: string;
  rating: number;
  totalReviews: number;
  address: string;
  types: string[];
  priceLevel?: number;
}

async function findCompetitors(businessName: string, city: string, industry: string): Promise<CompetitorData[]> {
  const query = `${industry} near ${city}`;
  const url = `https://maps.googleapis.com/maps/api/place/textsearch/json?query=${encodeURIComponent(query)}&key=${GOOGLE_MAPS_API_KEY}`;
  const res = await fetch(url);
  if (!res.ok) return [];
  const data = await res.json();
  const results = (data.results || []).slice(0, 15);
  return results
    .filter((r: any) => r.name?.toLowerCase() !== businessName?.toLowerCase())
    .map((r: any) => ({
      name: r.name || "Unknown",
      rating: r.rating || 0,
      totalReviews: r.user_ratings_total || 0,
      address: r.formatted_address || "",
      types: r.types || [],
      priceLevel: r.price_level,
    }));
}

function buildPrompt(businessName: string, city: string, industry: string, competitors: CompetitorData[]): string {
  const competitorBlock = competitors
    .map((c, i) => `${i + 1}. ${c.name} — Rating: ${c.rating}/5 (${c.totalReviews} reviews) — ${c.address}`)
    .join("\n");

  return `You are a senior local market strategist. Be brutally honest, data-driven, and actionable. Reference actual competitor names and real data.

Business: ${businessName}
City/Area: ${city}
Industry: ${industry}

Actual nearby competitors from Google Maps:
${competitorBlock}

Format the report EXACTLY as follows:

# Local Competitor Analysis Report
**${businessName}** — ${city}
*Generated by M² Development — mattmichelstraining.com — (313) 806-4952*

---

## Market Overview
[3-4 sentences: competitive density, average ratings, market health. Total competitors found and average review count.]

---

## Competitive Landscape

[For each of the top 8-10 competitors:]

### [Competitor Name] — ⭐ [rating]/5 ([X] reviews)
- **Win Rate:** [Calculate: (rating × review_count) / (5 × max_reviews_in_market) × 100]% — [what this means]
- **Strengths:** [What they do well]
- **Vulnerability:** [Where they're weak]
- **How to Beat Them:** [1-2 specific tactical moves ${businessName} should make against THIS competitor]
- **Threat Level:** [Low / Medium / High] — [1 sentence why]

---

## SWOT Summary

| | Favorable | Unfavorable |
|---|---|---|
| **Internal** | **Strengths:** [2-3 bullet points] | **Weaknesses:** [2-3 bullet points] |
| **External** | **Opportunities:** [2-3 bullet points] | **Threats:** [2-3 bullet points] |

---

## Review Gap Analysis
[Who has the most reviews and why. Average rating. Where ${businessName} sits. Specific review count targets to dominate.]

### 🔧 How to Close the Gap
- [Specific step — e.g. "Send a review request text/email after every completed job using a tool like Podium or BirdEye"]
- [Specific step — e.g. "Respond to every existing review within 24 hours — Google rewards engagement"]
- [Specific step]

---

## Positioning Opportunities
[3-4 specific gaps: underserved niches, geographic sub-areas, uncovered service categories, pricing tier gaps]

### 🔧 How to Exploit These Gaps
- [Specific action for gap #1]
- [Specific action for gap #2]
- [Specific action for gap #3]

---

## 🏃 30-Day Sprint Plan
Do these in order, one per week:

**Week 1:** [Specific action with expected outcome]
**Week 2:** [Specific action with expected outcome]
**Week 3:** [Specific action with expected outcome]
**Week 4:** [Specific action with expected outcome]

---

## Top 5 Action Items
1. **[Action]**: [Specific recommendation with expected impact]
2. **[Action]**: [Specific recommendation]
3. **[Action]**: [Specific recommendation]
4. **[Action]**: [Specific recommendation]
5. **[Action]**: [Specific recommendation]

---
*This report was generated by M² Development. mattmichelstraining.com*`;
}

async function generateReport(businessName: string, city: string, industry: string, competitors: CompetitorData[]): Promise<string> {
  const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${LOVABLE_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "google/gemini-2.5-flash",
      messages: [{ role: "user", content: buildPrompt(businessName, city, industry, competitors) }],
      max_tokens: 2500,
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`AI Gateway error: ${err}`);
  }

  const data = await response.json();
  return data.choices?.[0]?.message?.content || "";
}

async function sendReportEmail(email: string, businessName: string, reportText: string): Promise<void> {
  const htmlBody = reportText
    .replace(/^# (.+)$/gm, "<h1 style='color:#1e293b;font-family:Georgia,serif;margin-bottom:4px'>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2 style='color:#e8621a;font-family:Georgia,serif;margin-top:32px;margin-bottom:8px;font-size:18px'>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3 style='color:#1e293b;font-family:sans-serif;margin-top:16px;margin-bottom:6px;font-size:15px'>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^---$/gm, "<hr style='border:none;border-top:1px solid #e2e8f0;margin:20px 0'>")
    .replace(/^- (.+)$/gm, "<div style='padding:2px 0 2px 16px;font-size:14px;color:#475569'>• $1</div>")
    .replace(/^\d+\. (.+)$/gm, "<div style='padding:3px 0 3px 16px;font-size:14px;color:#475569'>$&</div>")
    .replace(/\|(.+)\|/g, (match) => {
      const cells = match.split("|").filter(c => c.trim());
      return `<div style="display:flex;gap:8px;padding:4px 0;font-size:13px;color:#475569">${cells.map(c => `<span style="flex:1">${c.trim()}</span>`).join("")}</div>`;
    })
    .replace(/\n\n/g, "</p><p style='margin:0 0 12px;color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px'>")
    .replace(/\n/g, "<br>");

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08)">
    <div style="background:#1e293b;padding:28px 32px">
      <p style="color:#e8621a;font-weight:700;font-size:12px;letter-spacing:.15em;text-transform:uppercase;margin:0 0 4px">M² Development</p>
      <h1 style="color:#fff;margin:0;font-family:Georgia,serif;font-size:22px">Your Competitor Analysis Is Ready</h1>
      <p style="color:#94a3b8;margin:8px 0 0;font-size:14px">For: ${businessName || email}</p>
    </div>
    <div style="padding:32px">
      <p style="color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px;margin:0 0 24px">
        Here's your AI-powered competitor analysis with <strong>real Google Maps data</strong>. Includes Win Rates, SWOT analysis, a 30-Day Sprint plan, and specific tactics to beat each competitor.
      </p>
      <div style="background:#f8fafc;border-radius:6px;padding:24px;border:1px solid #e2e8f0">
        <p style="margin:0 0 12px;color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px">${htmlBody}</p>
      </div>

      <!-- UPSELL: Website Audit -->
      <div style="margin-top:28px;padding:20px;background:#fef3c7;border-radius:8px;border:1px solid #fbbf24">
        <p style="margin:0 0 6px;font-weight:700;color:#92400e;font-size:15px;font-family:sans-serif">🔍 Get a Full Website Audit — $9</p>
        <p style="margin:0 0 12px;color:#78350f;font-size:13px;font-family:sans-serif;line-height:1.6">
          Find out what's holding your website back — 8 scored sections with specific "How to Fix" steps. Know exactly where you're losing leads.
        </p>
        <a href="https://www.mattmichelstraining.com/website-audit" style="display:inline-block;background:#e8621a;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:700;font-size:13px;font-family:sans-serif">Get Your Website Audit →</a>
      </div>

      <!-- UPSELL: GBP Management -->
      <div style="margin-top:16px;padding:20px;background:#fff7ed;border-radius:8px;border:1px solid #fed7aa">
        <p style="margin:0 0 6px;font-weight:700;color:#9a3412;font-size:15px;font-family:sans-serif">📍 Dominate Google? GBP Autopilot — $49/mo</p>
        <p style="margin:0 0 12px;color:#9a3412;font-size:13px;font-family:sans-serif;line-height:1.6">
          We post to your Google Business Profile 3x/week on autopilot. Active profiles rank higher in the map pack — where most local clicks happen.
        </p>
        <a href="https://www.mattmichelstraining.com/local-marketing" style="display:inline-block;background:#1e293b;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:700;font-size:13px;font-family:sans-serif">See GBP Management →</a>
      </div>

      <div style="margin-top:24px;padding:20px;background:#f8fafc;border-radius:6px;border:1px solid #e2e8f0">
        <p style="margin:0 0 8px;font-weight:700;color:#1e293b;font-family:sans-serif">Questions about your report?</p>
        <p style="margin:0;color:#475569;font-size:14px;font-family:sans-serif">
          Call or text Matt directly: <a href="tel:3138064952" style="color:#e8621a;font-weight:700">(313) 806-4952</a><br>
          Or reply to this email — I read every one.
        </p>
      </div>
    </div>
    <div style="padding:16px 32px;background:#f8fafc;border-top:1px solid #e2e8f0;text-align:center">
      <p style="margin:0;color:#94a3b8;font-size:12px;font-family:sans-serif">
        M² Development · mattmichelstraining.com · Grosse Pointe, MI<br>
        <a href="https://www.mattmichelstraining.com/detroit-web-design" style="color:#e8621a">View our work</a>
      </p>
    </div>
  </div>
</body></html>`;

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      from: "Matt Michels <matt@mattmichelstraining.com>",
      to: [email],
      bcc: ["matthewmichels4@gmail.com"],
      subject: `Your Competitor Analysis — ${businessName || "M² Development"}`,
      html,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Resend error: ${err}`);
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { email, business_name, city, industry, order_id } = await req.json();

    if (!email || !city || !industry) {
      return new Response(
        JSON.stringify({ error: "email, city, and industry are required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

    if (order_id) {
      const { data: existing } = await sb.from("competitor_reports").select("status,report_text").eq("id", order_id).maybeSingle();
      if (existing?.status === "delivered") {
        console.log(`[competitor-report] Already delivered for order ${order_id}`);
        return new Response(JSON.stringify({ ok: true, cached: true }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
    }

    if (order_id) {
      await sb.from("competitor_reports").update({ status: "processing" }).eq("id", order_id);
    }

    const competitors = await findCompetitors(business_name || "", city, industry);
    console.log(`[competitor-report] Found ${competitors.length} competitors for ${industry} in ${city}`);

    const reportText = await generateReport(business_name || "", city, industry, competitors);
    await sendReportEmail(email, business_name || city, reportText);

    const updatePayload = { status: "delivered", report_text: reportText, competitors_json: JSON.stringify(competitors) };
    if (order_id) {
      await sb.from("competitor_reports").update(updatePayload).eq("id", order_id);
    } else {
      await sb.from("competitor_reports").insert({ email, business_name: business_name || null, city, industry, ...updatePayload });
    }

    console.log(`[competitor-report] Report delivered to ${email} for ${industry} in ${city}`);

    return new Response(JSON.stringify({ ok: true }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err: any) {
    console.error("[competitor-report]", err);
    try {
      const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);
      const body = await req.clone().json().catch(() => ({}));
      await sb.from("delivery_failures").insert({
        function_name: "competitor-report",
        error_message: err.message,
        customer_email: body.email || null,
        order_id: body.order_id || null,
      });
      if (RESEND_API_KEY) {
        await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            from: "M² Alerts <matt@mattmichelstraining.com>",
            to: ["matt@mattmichelstraining.com"],
            subject: `🚨 DELIVERY FAILED — competitor-report — ${body.email || "unknown"}`,
            html: `<p><strong>Function:</strong> competitor-report</p><p><strong>Customer:</strong> ${body.email || "unknown"}</p><p><strong>Error:</strong> ${err.message}</p>`,
          }),
        });
      }
    } catch (alertErr) { console.error("[competitor-report] Alert failed:", alertErr); }
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
