import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SUPABASE_SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY") || "";
const GOOGLE_MAPS_API_KEY = Deno.env.get("GOOGLE_MAPS_API_KEY") || "";
const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") || "";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface CompetitorData {
  name: string;
  rating: number;
  totalReviews: number;
  address: string;
  types: string[];
  priceLevel?: number;
}

async function findCompetitors(
  businessName: string,
  city: string,
  industry: string,
): Promise<CompetitorData[]> {
  const query = `${industry} near ${city}`;
  const url = `https://maps.googleapis.com/maps/api/place/textsearch/json?query=${encodeURIComponent(query)}&key=${GOOGLE_MAPS_API_KEY}`;
  const res = await fetch(url);
  if (!res.ok) return [];
  const data = await res.json();
  const results = (data.results || []).slice(0, 15);

  return results
    .filter((r: any) => r.name?.toLowerCase() !== businessName?.toLowerCase())
    .map((r: any) => ({
      name: r.name || "Unknown",
      rating: r.rating || 0,
      totalReviews: r.user_ratings_total || 0,
      address: r.formatted_address || "",
      types: r.types || [],
      priceLevel: r.price_level,
    }));
}

function buildPrompt(
  businessName: string,
  city: string,
  industry: string,
  competitors: CompetitorData[],
): string {
  const competitorBlock = competitors
    .map(
      (c, i) =>
        `${i + 1}. ${c.name} — Rating: ${c.rating}/5 (${c.totalReviews} reviews) — ${c.address}`,
    )
    .join("\n");

  return `You are a senior local market strategist conducting a competitive landscape analysis for a real business.

Business: ${businessName}
City/Area: ${city}
Industry: ${industry}

Here are the actual nearby competitors from Google Maps:
${competitorBlock}

Generate a detailed, actionable competitor analysis report. Be specific, data-driven, and brutally honest. Reference actual competitor names and their real review counts/ratings.

Format the report exactly as follows:

# Local Competitor Analysis Report
**${businessName}** — ${city}
*Generated by M² Web Design — mattmichelstraining.com — (313) 806-4952*

---

## Market Overview
[3-4 sentences summarizing the competitive density, average ratings, and overall market health for ${industry} in ${city}. Mention total competitors found and average review count.]

---

## Competitive Landscape

[For each of the top 8-10 competitors, provide a brief analysis:]

### [Competitor Name] — ⭐ [rating]/5 ([X] reviews)
- **Strengths:** [What they're doing well based on review count, rating, positioning]
- **Vulnerability:** [Where they're weak — low reviews, declining rating, poor web presence, etc.]
- **Threat Level:** [Low / Medium / High] — [1 sentence why]

---

## Review Gap Analysis
[Analyze the review landscape:
- Who has the most reviews and why that matters
- The average rating in this market
- Where ${businessName} sits relative to the competition
- Specific review count targets to become dominant]

---

## Positioning Opportunities
[Identify 3-4 specific gaps in the market that ${businessName} can exploit:
- Underserved niches or specialties
- Geographic sub-areas with less competition
- Service categories competitors aren't covering
- Pricing tier opportunities]

---

## Top 5 Action Items
1. **[Action title]**: [Specific, actionable recommendation with expected impact]
2. **[Action title]**: [Specific recommendation]
3. **[Action title]**: [Specific recommendation]
4. **[Action title]**: [Specific recommendation]
5. **[Action title]**: [Specific recommendation]

---

## Need Help Executing?
A professional web presence overhaul — with local SEO, review management, and conversion optimization — typically costs $1,499–$3,499 and pays for itself within 90 days of increased leads.

**Ready to dominate your local market?** Reply to this email or call Matt at (313) 806-4952.

---
*This report was generated by M² Web Design. mattmichelstraining.com*`;
}

async function generateReport(
  businessName: string,
  city: string,
  industry: string,
  competitors: CompetitorData[],
): Promise<string> {
  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 2000,
      messages: [
        { role: "user", content: buildPrompt(businessName, city, industry, competitors) },
      ],
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Claude API error: ${err}`);
  }

  const data = await response.json();
  return data.content?.[0]?.text || "";
}

async function sendReportEmail(
  email: string,
  businessName: string,
  reportText: string,
): Promise<void> {
  const htmlBody = reportText
    .replace(
      /^# (.+)$/gm,
      "<h1 style='color:#1e293b;font-family:Georgia,serif;margin-bottom:4px'>$1</h1>",
    )
    .replace(
      /^## (.+)$/gm,
      "<h2 style='color:#e8621a;font-family:Georgia,serif;margin-top:32px;margin-bottom:8px;font-size:18px'>$1</h2>",
    )
    .replace(
      /^### (.+)$/gm,
      "<h3 style='color:#1e293b;font-family:sans-serif;margin-top:20px;margin-bottom:6px;font-size:16px'>$1</h3>",
    )
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^---$/gm, "<hr style='border:none;border-top:1px solid #e2e8f0;margin:20px 0'>")
    .replace(
      /\n\n/g,
      "</p><p style='margin:0 0 12px;color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px'>",
    )
    .replace(/\n/g, "<br>");

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08)">
    <div style="background:#1e293b;padding:28px 32px">
      <p style="color:#e8621a;font-weight:700;font-size:12px;letter-spacing:.15em;text-transform:uppercase;margin:0 0 4px">M² Web Design</p>
      <h1 style="color:#fff;margin:0;font-family:Georgia,serif;font-size:22px">Your Competitor Analysis Is Ready</h1>
      <p style="color:#94a3b8;margin:8px 0 0;font-size:14px">For: ${businessName || email}</p>
    </div>
    <div style="padding:32px">
      <p style="color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px;margin:0 0 24px">
        Here's your AI-powered local competitor analysis. We pulled real data from Google Maps about your nearby competitors and analyzed their strengths, weaknesses, and the gaps you can exploit.
      </p>
      <div style="background:#f8fafc;border-radius:6px;padding:24px;border:1px solid #e2e8f0">
        <p style="margin:0 0 12px;color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px">${htmlBody}</p>
      </div>
      <div style="margin-top:32px;padding:20px;background:#fff7ed;border-radius:6px;border:1px solid #fed7aa">
        <p style="margin:0 0 8px;font-weight:700;color:#1e293b;font-family:sans-serif">Questions about your report?</p>
        <p style="margin:0;color:#475569;font-size:14px;font-family:sans-serif">
          Call or text Matt directly: <a href="tel:3138064952" style="color:#e8621a;font-weight:700">(313) 806-4952</a><br>
          Or reply to this email — I read every one.
        </p>
      </div>
    </div>
    <div style="padding:16px 32px;background:#f8fafc;border-top:1px solid #e2e8f0;text-align:center">
      <p style="margin:0;color:#94a3b8;font-size:12px;font-family:sans-serif">
        M² Web Design · mattmichelstraining.com · Grosse Pointe, MI<br>
        <a href="https://www.mattmichelstraining.com/detroit-web-design" style="color:#e8621a">View our work</a>
      </p>
    </div>
  </div>
</body>
</html>`;

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: "Matt Michels <matt@mattmichelstraining.com>",
      to: [email],
      subject: `Your Competitor Analysis — ${businessName || "M² Web Design"}`,
      html,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Resend error: ${err}`);
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { email, business_name, city, industry, order_id } = await req.json();

    if (!email || !city || !industry) {
      return new Response(
        JSON.stringify({ error: "email, city, and industry are required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

    // Idempotency check
    if (order_id) {
      const { data: existing } = await sb
        .from("competitor_reports")
        .select("status,report_text")
        .eq("id", order_id)
        .maybeSingle();
      if (existing?.status === "delivered") {
        console.log(`[competitor-report] Already delivered for order ${order_id}`);
        return new Response(JSON.stringify({ ok: true, cached: true }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
    }

    // Mark processing
    if (order_id) {
      await sb.from("competitor_reports").update({ status: "processing" }).eq("id", order_id);
    }

    // Pull real competitor data from Google Maps
    const competitors = await findCompetitors(business_name || "", city, industry);
    console.log(
      `[competitor-report] Found ${competitors.length} competitors for ${industry} in ${city}`,
    );

    // Generate report via Claude
    const reportText = await generateReport(
      business_name || "",
      city,
      industry,
      competitors,
    );

    // Send email
    await sendReportEmail(email, business_name || city, reportText);

    // Update order record
    const updatePayload = {
      status: "delivered",
      report_text: reportText,
      competitors_json: JSON.stringify(competitors),
    };
    if (order_id) {
      await sb.from("competitor_reports").update(updatePayload).eq("id", order_id);
    } else {
      await sb.from("competitor_reports").insert({
        email,
        business_name: business_name || null,
        city,
        industry,
        ...updatePayload,
      });
    }

    console.log(`[competitor-report] Report delivered to ${email} for ${industry} in ${city}`);

    return new Response(JSON.stringify({ ok: true }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err: any) {
    console.error("[competitor-report]", err);
    try {
      await fetch(`${SUPABASE_URL}/rest/v1/delivery_failures`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "apikey": SUPABASE_SERVICE_KEY, "Authorization": `Bearer ${SUPABASE_SERVICE_KEY}`, "Prefer": "return=minimal" },
        body: JSON.stringify({ function_name: "competitor-report", error_message: err.message || String(err) }),
      });
    } catch (_) {}
    try {
      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: { "Authorization": `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          from: "Matt Michels <matt@mattmichelstraining.com>",
          to: "matt@mattmichelstraining.com",
          subject: "⚠️ Delivery Failed: competitor-report",
          html: `<p><strong>Function:</strong> competitor-report</p><p><strong>Error:</strong> ${err.message || String(err)}</p><p><strong>Time:</strong> ${new Date().toISOString()}</p>`,
        }),
      });
    } catch (_) {}
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
