import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY") || "";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };

// AI response type
// uses OpenAI-compatible format



const EMAIL_SIGNATURE = `<div style="margin-top:24px;padding-top:16px;border-top:1px solid #334155;display:flex;align-items:center;gap:12px;"><img src="https://www.mattmichelstraining.com/images/matt-boat.jpg" alt="Matt Michels" style="width:48px;height:48px;border-radius:50%;object-fit:cover;" /><div style="font-size:13px;color:#94a3b8;"><strong style="color:#e2e8f0;">Matt Michels</strong><br/>Grosse Pointe, MI · (313) 806-4952</div><img src="https://www.mattmichelstraining.com/images/m2-development-logo.png" alt="M2 Development" style="width:36px;height:36px;margin-left:auto;object-fit:contain;" /></div>`;

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: clients, error: clientsError } = await supabase
      .from("competitor_watch_clients")
      .select("*")
      .eq("active", true);

    if (clientsError) throw clientsError;
    if (!clients || clients.length === 0) {
      return new Response(JSON.stringify({ message: "No active clients" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    let processed = 0;

    for (const client of clients) {
      const prompt = `You are a competitive intelligence analyst. Generate a competitor analysis report for a ${client.industry} business located in ${client.city}, ${client.state || "MI"}.

Business name: ${client.business_name}

Include these sections:
1. **Market Overview** — Brief overview of the local ${client.industry} market in ${client.city}
2. **Top Competitors** — List 5 likely competitors with strengths and weaknesses
3. **Competitive Advantages** — What ${client.business_name} can leverage
4. **Threats to Watch** — Emerging trends or competitor moves
5. **Recommended Actions** — 3-5 specific action items for this month

Write in professional but accessible language. Use HTML formatting with <h2>, <p>, <ul>, <li>, <strong> tags.`;

      const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${LOVABLE_API_KEY}` },
        body: JSON.stringify({
          model: "google/gemini-2.5-flash-lite", 
          messages: [{ role: "user", content: prompt }] }) });

      const aiData = await aiResponse.json() as any;
      const reportHtml = aiData?.choices?.[0]?.message?.content || "Report generation failed.";

      const emailHtml = `
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: Arial, sans-serif; color: #1e293b; max-width: 700px; margin: 0 auto; padding: 20px; }
  h1 { color: #e8621a; border-bottom: 2px solid #e8621a; padding-bottom: 10px; }
  h2 { color: #1e293b; margin-top: 24px; }
  ul { padding-left: 20px; }
  li { margin-bottom: 8px; }
  .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 13px; color: #666; }
</style></head>
<body>
  <h1>🔍 Competitor Watch Report — ${client.business_name}</h1>
  <p style="color:#666;">Generated ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
  ${reportHtml}
  <div class="footer">
    <p>This report was generated by M2 Development's AI Competitor Watch service.</p>
    <p>Questions? Reply to this email or text Matt at (313) 806-4952.</p>
  </div>
</body>
</html>`;

      const emailRes = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${Deno.env.get("RESEND_API_KEY")}` },
        body: JSON.stringify({
          from: "M² Competitor Watch <matt@mattmichelstraining.com>",
          to: [client.email], bcc: ["matthewmichels4@gmail.com"],
          subject: `Competitor Watch Report — ${client.business_name} — ${new Date().toLocaleDateString("en-US", { month: "short", year: "numeric" })}`,
          html: emailHtml}) });

      if (!emailRes.ok) {
        console.error(`Failed to email ${client.email}:`, await emailRes.text());
        continue;
      }

      await supabase
        .from("competitor_watch_clients")
        .update({
          report_count: (client.report_count || 0) + 1,
          last_report_at: new Date().toISOString() })
        .eq("id", client.id);

      processed++;
    }

    return new Response(
      JSON.stringify({ success: true, processed }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("ai-competitor-watch error:", error);
    const message = error instanceof Error ? error.message : String(error);
    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
