import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SUPABASE_SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY") || "";
const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") || "";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function buildAuditPrompt(businessName: string, businessUrl: string): string {
  return `You are a senior digital marketing consultant conducting a professional website audit for a paying client. Be brutally honest, hyper-specific, and actionable. Write as if you've actually reviewed their site.

Business: ${businessName || "the business at this URL"}
Website URL: ${businessUrl}

Format the report EXACTLY as follows:

# AI Website Audit Report
**${businessName || businessUrl}**
*Generated by M² Development — mattmichelstraining.com — (313) 806-4952*

---

## Overall Score: [X/100]
[2-3 sentence executive summary. Be specific about their biggest win and biggest gap.]

---

## 1. First Impression & Design (Score: X/10)
[3-4 specific observations about visual design, brand consistency, modernity]

**Key Issue:** [Single biggest design problem]

### 🔧 How to Fix It
- [Specific DIY step 1 with tool/resource to use]
- [Specific DIY step 2]
- [Specific DIY step 3]

**⚡ Quick Win** or **🎯 Long Game** — [label this recommendation]

---

## 2. Mobile Experience (Score: X/10)
[3-4 specific observations about responsiveness, tap targets, mobile speed]

**Key Issue:** [Single biggest mobile problem]

### 🔧 How to Fix It
- [Specific step — e.g. "Add viewport meta tag", "Use Google's Mobile-Friendly Test at search.google.com/test/mobile-friendly"]
- [Specific step]

**⚡ Quick Win** or **🎯 Long Game**

---

## 3. Local SEO Signals (Score: X/10)
[3-4 observations: city mentions, NAP consistency, GBP integration, local keywords]

**Key Issue:** [Biggest local SEO gap]

### 🔧 How to Fix It
- [Specific step — e.g. "Add your city name to your homepage H1 and title tag"]
- [Specific step]
- [Specific step]

**⚡ Quick Win** or **🎯 Long Game**

---

## 4. Trust & Credibility (Score: X/10)
[3-4 observations: reviews visible? credentials? SSL? real photos?]

**Key Issue:** [Biggest trust gap]

### 🔧 How to Fix It
- [Specific step]
- [Specific step]

**⚡ Quick Win** or **🎯 Long Game**

---

## 5. Calls to Action & Conversion (Score: X/10)
[3-4 observations: phone prominence, form placement, clear next step]

**Key Issue:** [Biggest conversion problem]

### 🔧 How to Fix It
- [Specific step]
- [Specific step]

**⚡ Quick Win** or **🎯 Long Game**

---

## 6. Content & Copy (Score: X/10)
[3-4 observations: value prop clarity, benefits vs features, freshness]

**Key Issue:** [Biggest content problem]

### 🔧 How to Fix It
- [Specific step]
- [Specific step]

**⚡ Quick Win** or **🎯 Long Game**

---

## 7. Page Speed & Performance (Score: X/10)
[Analyze likely page speed issues: large images, unminified code, no caching, render-blocking scripts, no lazy loading. Be specific about what's probably slowing them down based on the type of site.]

**Key Issue:** [Biggest speed problem]

### 🔧 How to Fix It
- [e.g. "Compress images using TinyPNG.com — most business sites have 2-5MB hero images that should be under 200KB"]
- [e.g. "Enable browser caching via .htaccess or your hosting panel"]
- [Specific step]

**⚡ Quick Win**

---

## 8. Content Freshness & Quality (Score: X/10)
[Is the site updated recently? Is there a blog? Are service descriptions detailed or thin? Any duplicate content issues?]

**Key Issue:** [Biggest freshness problem]

### 🔧 How to Fix It
- [e.g. "Add a blog and publish 1 post per month targeting a local keyword"]
- [Specific step]

**🎯 Long Game**

---

## ✅ 5-Point Action Checklist (Do These First)
1. **[Highest-impact fix]** — ⚡ Quick Win — [Expected result]
2. **[Second priority]** — ⚡ Quick Win — [Expected result]
3. **[Third priority]** — [Quick Win or Long Game] — [Expected result]
4. **[Fourth priority]** — 🎯 Long Game — [Expected result]
5. **[Fifth priority]** — 🎯 Long Game — [Expected result]

---

## Investment to Fix This Right
A professional redesign addressing all 8 areas typically costs $499–$3,499 depending on complexity, plus optional monthly retainer for SEO and updates. Most clients see measurable lead improvement within 60–90 days.

**Ready to talk?** Reply to this email or call Matt directly at (313) 806-4952.

---
*This report was generated by M² Development. mattmichelstraining.com*`;
}

async function generateAudit(businessName: string, businessUrl: string): Promise<string> {
  const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${LOVABLE_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "google/gemini-2.5-flash",
      messages: [{ role: "user", content: buildAuditPrompt(businessName, businessUrl) }],
      max_tokens: 2000,
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`AI Gateway error: ${err}`);
  }

  const data = await response.json();
  return data.choices?.[0]?.message?.content || "";
}

async function sendAuditEmail(email: string, businessName: string, reportText: string): Promise<void> {
  const htmlBody = reportText
    .replace(/^# (.+)$/gm, "<h1 style='color:#1e293b;font-family:Georgia,serif;margin-bottom:4px'>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2 style='color:#e8621a;font-family:Georgia,serif;margin-top:32px;margin-bottom:8px;font-size:18px'>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3 style='color:#1e293b;font-family:sans-serif;margin-top:16px;margin-bottom:6px;font-size:15px'>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^---$/gm, "<hr style='border:none;border-top:1px solid #e2e8f0;margin:20px 0'>")
    .replace(/^- (.+)$/gm, "<div style='padding:2px 0 2px 16px;font-size:14px;color:#475569'>• $1</div>")
    .replace(/^\d+\. (.+)$/gm, "<div style='padding:3px 0 3px 16px;font-size:14px;color:#475569'>$&</div>")
    .replace(/\n\n/g, "</p><p style='margin:0 0 12px;color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px'>")
    .replace(/\n/g, "<br>");

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08)">
    <div style="background:#1e293b;padding:28px 32px">
      <p style="color:#e8621a;font-weight:700;font-size:12px;letter-spacing:.15em;text-transform:uppercase;margin:0 0 4px">M² Development</p>
      <h1 style="color:#fff;margin:0;font-family:Georgia,serif;font-size:22px">Your Website Audit Is Ready</h1>
      <p style="color:#94a3b8;margin:8px 0 0;font-size:14px">For: ${businessName || email}</p>
    </div>
    <div style="padding:32px">
      <p style="color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px;margin:0 0 24px">
        Here's your full AI website audit — <strong>8 scored sections</strong> with specific "How to Fix It" steps for each one. Start with the <strong>5-Point Action Checklist</strong> at the bottom for the fastest wins.
      </p>
      <div style="background:#f8fafc;border-radius:6px;padding:24px;border:1px solid #e2e8f0">
        <p style="margin:0 0 12px;color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px">${htmlBody}</p>
      </div>

      <!-- UPSELL: Competitor Report -->
      <div style="margin-top:28px;padding:20px;background:#fef3c7;border-radius:8px;border:1px solid #fbbf24">
        <p style="margin:0 0 6px;font-weight:700;color:#92400e;font-size:15px;font-family:sans-serif">📊 See How You Stack Up Against Competitors — $9</p>
        <p style="margin:0 0 12px;color:#78350f;font-size:13px;font-family:sans-serif;line-height:1.6">
          Get a full competitive landscape analysis with real Google Maps data — win rates, threat levels, and a 30-day action sprint to outrank your competitors.
        </p>
        <a href="https://www.mattmichelstraining.com/competitor-report" style="display:inline-block;background:#e8621a;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:700;font-size:13px;font-family:sans-serif">Get Your Competitor Report →</a>
      </div>

      <!-- UPSELL: Web Design -->
      <div style="margin-top:16px;padding:20px;background:#fff7ed;border-radius:8px;border:1px solid #fed7aa">
        <p style="margin:0 0 6px;font-weight:700;color:#9a3412;font-size:15px;font-family:sans-serif">🔨 Want Us to Fix Everything? Web design packages from $499</p>
        <p style="margin:0 0 12px;color:#9a3412;font-size:13px;font-family:sans-serif;line-height:1.6">
          We'll rebuild your site addressing every issue in this audit — mobile-first, SEO-optimized, conversion-focused. Most clients see results within 60 days.
        </p>
        <a href="https://www.mattmichelstraining.com/detroit-web-design" style="display:inline-block;background:#1e293b;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:700;font-size:13px;font-family:sans-serif">View Web Design Packages →</a>
      </div>

      <div style="margin-top:24px;padding:20px;background:#f8fafc;border-radius:6px;border:1px solid #e2e8f0">
        <p style="margin:0 0 8px;font-weight:700;color:#1e293b;font-family:sans-serif">Questions about your audit?</p>
        <p style="margin:0;color:#475569;font-size:14px;font-family:sans-serif">
          Call or text Matt directly: <a href="tel:3138064952" style="color:#e8621a;font-weight:700">(313) 806-4952</a><br>
          Or reply to this email — I read every one.
        </p>
      </div>
    </div>
    <div style="padding:16px 32px;background:#f8fafc;border-top:1px solid #e2e8f0;text-align:center">
      <p style="margin:0;color:#94a3b8;font-size:12px;font-family:sans-serif">
        M² Development · mattmichelstraining.com · Grosse Pointe, MI<br>
        <a href="https://www.mattmichelstraining.com/detroit-web-design" style="color:#e8621a">View our work</a>
      </p>
    </div>
  </div>
</body></html>`;

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: "Matt Michels <matt@mattmichelstraining.com>",
      to: [email],
      bcc: ["matthewmichels4@gmail.com"],
      subject: `Your Website Audit — ${businessName || "M² Development"}`,
      html,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Resend error: ${err}`);
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { email, business_name, business_url, order_id } = await req.json();

    if (!email || !business_url) {
      return new Response(JSON.stringify({ error: "email and business_url are required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

    if (order_id) {
      const { data: existing } = await sb.from("audit_orders").select("status,report_text").eq("id", order_id).maybeSingle();
      if (existing?.status === "delivered") {
        console.log(`[instant-audit] Already delivered for order ${order_id}`);
        return new Response(JSON.stringify({ ok: true, cached: true }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
    }

    if (order_id) {
      await sb.from("audit_orders").update({ status: "processing" }).eq("id", order_id);
    }

    const reportText = await generateAudit(business_name || "", business_url);
    await sendAuditEmail(email, business_name || business_url, reportText);

    const updatePayload: Record<string, string> = { status: "delivered", report_text: reportText };
    if (order_id) {
      await sb.from("audit_orders").update(updatePayload).eq("id", order_id);
    } else {
      await sb.from("audit_orders").insert({ email, business_name: business_name || null, business_url, status: "delivered", report_text: reportText });
    }

    console.log(`[instant-audit] Audit delivered to ${email} for ${business_url}`);

    return new Response(JSON.stringify({ ok: true }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err: any) {
    console.error("[instant-audit]", err);
    try {
      const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);
      const body = await req.clone().json().catch(() => ({}));
      await sb.from("delivery_failures").insert({
        function_name: "instant-audit",
        error_message: err.message,
        customer_email: body.email || null,
        order_id: body.order_id || null,
      });
      if (RESEND_API_KEY) {
        await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            from: "M² Alerts <matt@mattmichelstraining.com>",
            to: ["matt@mattmichelstraining.com"],
            subject: `🚨 DELIVERY FAILED — instant-audit — ${body.email || "unknown"}`,
            html: `<p><strong>Function:</strong> instant-audit</p><p><strong>Customer:</strong> ${body.email || "unknown"}</p><p><strong>Error:</strong> ${err.message}</p><p><strong>Time:</strong> ${new Date().toISOString()}</p>`,
          }),
        });
      }
    } catch (alertErr) { console.error("[instant-audit] Alert failed:", alertErr); }
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
