import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SUPABASE_SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY") || "";
const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") || "";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function buildAuditPrompt(businessName: string, businessUrl: string): string {
  return `You are a senior digital marketing consultant and web designer conducting a professional website audit.

Business: ${businessName || "the business at this URL"}
Website URL: ${businessUrl}

Generate a detailed, professional website audit report. Be honest and specific. Write as if you've actually reviewed their site (make realistic, specific observations based on common issues for this type of business/URL).

Format the report exactly as follows:

# AI Website Audit Report
**${businessName || businessUrl}**
*Generated by M² Web Design — mattmichelstraining.com — (313) 806-4952*

---

## Overall Score: [X/100]
[2-3 sentence executive summary of the site's current state and biggest opportunity]

---

## 1. First Impression & Design (Score: X/10)
[3-4 specific observations about visual design, modernity, brand consistency, professional appearance]

**Key Issue:** [The single biggest visual/design problem]

---

## 2. Mobile Experience (Score: X/10)
[3-4 specific observations about mobile responsiveness, load speed on mobile, tap targets, mobile navigation]

**Key Issue:** [The single biggest mobile problem]

---

## 3. Local SEO Signals (Score: X/10)
[3-4 specific observations: Is the city/region mentioned? NAP (name, address, phone) consistency? Google Business Profile integration? Local keywords?]

**Key Issue:** [The single biggest local SEO gap]

---

## 4. Trust & Credibility (Score: X/10)
[3-4 specific observations: reviews/testimonials visible? Credentials shown? Photos of real people? SSL? Years in business?]

**Key Issue:** [The single biggest trust gap]

---

## 5. Calls to Action & Conversion (Score: X/10)
[3-4 specific observations: Is the phone number prominent? Easy to contact? Clear next step for visitors? Form above the fold?]

**Key Issue:** [The single biggest conversion problem]

---

## 6. Content & Copy (Score: X/10)
[3-4 specific observations: Is the value proposition clear? Benefits vs. features? Readable? Updated recently?]

**Key Issue:** [The single biggest content problem]

---

## Top 3 Priority Fixes
1. **[Fix #1 title]**: [Specific, actionable recommendation — what exactly to change and why]
2. **[Fix #2 title]**: [Specific, actionable recommendation]
3. **[Fix #3 title]**: [Specific, actionable recommendation]

---

## Investment to Fix This Right
A professional redesign addressing all the issues above typically costs $1,499–$3,499 depending on complexity, plus a low monthly retainer for ongoing updates and SEO. Most clients see measurable lead improvement within 60–90 days of launch.

**Ready to talk?** Reply to this email or call Matt directly at (313) 806-4952.

---
*This report was generated by M² Web Design. mattmichelstraining.com*`;
}

async function generateAudit(businessName: string, businessUrl: string): Promise<string> {
  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 1800,
      messages: [{ role: "user", content: buildAuditPrompt(businessName, businessUrl) }],
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Claude API error: ${err}`);
  }

  const data = await response.json();
  return data.content?.[0]?.text || "";
}

async function sendAuditEmail(email: string, businessName: string, reportText: string): Promise<void> {
  // Convert markdown-ish report to basic HTML
  const htmlBody = reportText
    .replace(/^# (.+)$/gm, "<h1 style='color:#1e293b;font-family:Georgia,serif;margin-bottom:4px'>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2 style='color:#e8621a;font-family:Georgia,serif;margin-top:32px;margin-bottom:8px;font-size:18px'>$2</h2>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^---$/gm, "<hr style='border:none;border-top:1px solid #e2e8f0;margin:20px 0'>")
    .replace(/\n\n/g, "</p><p style='margin:0 0 12px;color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px'>")
    .replace(/\n/g, "<br>");

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08)">
    <div style="background:#1e293b;padding:28px 32px">
      <p style="color:#e8621a;font-weight:700;font-size:12px;letter-spacing:.15em;text-transform:uppercase;margin:0 0 4px">M² Web Design</p>
      <h1 style="color:#fff;margin:0;font-family:Georgia,serif;font-size:22px">Your Website Audit Is Ready</h1>
      <p style="color:#94a3b8;margin:8px 0 0;font-size:14px">For: ${businessName || email}</p>
    </div>
    <div style="padding:32px">
      <p style="color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px;margin:0 0 24px">
        Here's your full AI website audit. Read through the scoring sections and the <strong>Top 3 Priority Fixes</strong> at the bottom — those are where you'll get the fastest ROI.
      </p>
      <div style="background:#f8fafc;border-radius:6px;padding:24px;border:1px solid #e2e8f0">
        <p style="margin:0 0 12px;color:#475569;line-height:1.7;font-family:sans-serif;font-size:15px">${htmlBody}</p>
      </div>
      <div style="margin-top:32px;padding:20px;background:#fff7ed;border-radius:6px;border:1px solid #fed7aa">
        <p style="margin:0 0 8px;font-weight:700;color:#1e293b;font-family:sans-serif">Questions about your audit?</p>
        <p style="margin:0;color:#475569;font-size:14px;font-family:sans-serif">
          Call or text Matt directly: <a href="tel:3138064952" style="color:#e8621a;font-weight:700">(313) 806-4952</a><br>
          Or reply to this email — I read every one.
        </p>
      </div>
    </div>
    <div style="padding:16px 32px;background:#f8fafc;border-top:1px solid #e2e8f0;text-align:center">
      <p style="margin:0;color:#94a3b8;font-size:12px;font-family:sans-serif">
        M² Web Design · mattmichelstraining.com · Grosse Pointe, MI<br>
        <a href="https://www.mattmichelstraining.com/detroit-web-design" style="color:#e8621a">View our work</a>
      </p>
    </div>
  </div>
</body>
</html>`;

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: "Matt Michels <matt@mattmichelstraining.com>",
      to: [email],
      subject: `Your Website Audit — ${businessName || "M² Web Design"}`,
      html,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Resend error: ${err}`);
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { email, business_name, business_url, order_id } = await req.json();

    if (!email || !business_url) {
      return new Response(JSON.stringify({ error: "email and business_url are required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

    // Check idempotency — don't regenerate if already done
    if (order_id) {
      const { data: existing } = await sb.from("audit_orders").select("status,report_text").eq("id", order_id).maybeSingle();
      if (existing?.status === "delivered") {
        console.log(`[instant-audit] Already delivered for order ${order_id}`);
        return new Response(JSON.stringify({ ok: true, cached: true }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
    }

    // Mark as processing
    if (order_id) {
      await sb.from("audit_orders").update({ status: "processing" }).eq("id", order_id);
    }

    // Generate report
    const reportText = await generateAudit(business_name || "", business_url);

    // Send email
    await sendAuditEmail(email, business_name || business_url, reportText);

    // Update order record
    const updatePayload: Record<string, string> = { status: "delivered", report_text: reportText };
    if (order_id) {
      await sb.from("audit_orders").update(updatePayload).eq("id", order_id);
    } else {
      await sb.from("audit_orders").insert({ email, business_name: business_name || null, business_url, status: "delivered", report_text: reportText });
    }

    console.log(`[instant-audit] Audit delivered to ${email} for ${business_url}`);

    return new Response(JSON.stringify({ ok: true }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err: any) {
    console.error("[instant-audit]", err);
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
