import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SUPABASE_SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY") || "";
const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") || "";

serve(async (_req) => {
  const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);
  try {
    const { data: clients } = await sb.from("staff_newsletter_clients").select("*").eq("active", true);
    if (!clients?.length) return new Response(JSON.stringify({ ok: true, sent: 0 }), { status: 200 });
    let sent = 0;
    for (const client of clients) {
      try {
        const aiRes = await fetch("https://api.anthropic.com/v1/messages", {
          method: "POST",
          headers: { "x-api-key": ANTHROPIC_API_KEY, "anthropic-version": "2023-06-01", "Content-Type": "application/json" },
          body: JSON.stringify({
            model: "claude-haiku-4-5-20251001", max_tokens: 800,
            messages: [{ role: "user", content: `Write a short weekly internal staff newsletter for "${client.business_name}" (industry: ${client.industry || "general"}). Include: 1) One industry news item, 2) A safety or compliance tip, 3) A motivational quote or team shoutout template, 4) A fun fact. Keep it under 300 words. Format as HTML with headers.` }],
          }),
        });
        const aiData = await aiRes.json();
        const content = aiData?.content?.[0]?.text || "<p>Newsletter content unavailable this week.</p>";
        if (RESEND_API_KEY) {
          await fetch("https://api.resend.com/emails", {
            method: "POST",
            headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
            body: JSON.stringify({
              from: "M² Staff Newsletter <matt@notify.m2training.com>", to: [client.email],
              subject: `This Week's Team Newsletter — ${client.business_name}`,
              html: `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;">${content}<hr style="margin:20px 0;border:none;border-top:1px solid #e2e8f0;"><p style="color:#94a3b8;font-size:12px;">Forward this to your team. Generated by M² AI Newsletter Service.</p></div>`,
            }),
          });
        }
        await sb.from("staff_newsletter_clients").update({ newsletter_count: (client.newsletter_count || 0) + 1 }).eq("id", client.id);
        sent++;
      } catch (e) { console.error(`[STAFF-NEWSLETTER] Error for ${client.email}:`, e); }
    }
    return new Response(JSON.stringify({ ok: true, sent }), { status: 200 });
  } catch (e: any) { console.error("[STAFF-NEWSLETTER] Fatal:", e); return new Response(JSON.stringify({ error: e.message }), { status: 500 }); }
});
