import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }

  try {
    const { clientEmail, projectDescription, prospectName, prospectEmail } = await req.json();

    if (!clientEmail || !projectDescription || !prospectName || !prospectEmail) {
      return new Response(
        JSON.stringify({ error: "Missing required fields: clientEmail, projectDescription, prospectName, prospectEmail" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: client, error: clientError } = await supabase
      .from("estimate_generator_clients")
      .select("*")
      .eq("email", clientEmail)
      .eq("active", true)
      .single();

    if (clientError || !client) {
      return new Response(
        JSON.stringify({ error: "Client not found or inactive" }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const prompt = `You are a professional estimator for ${client.business_name}, a ${client.industry} company in ${client.city}, ${client.state || "MI"}.

Generate a professional project estimate for the following request from ${prospectName}:

"${projectDescription}"

Include these sections in HTML format:
1. <h2>Scope of Work</h2> — Detailed description of what's included
2. <h2>Line Items</h2> — A table with columns: Item, Description, Estimated Cost. Include 4-8 realistic line items with dollar amounts. Add a total row.
3. <h2>Timeline</h2> — Estimated project duration with milestones
4. <h2>Terms & Conditions</h2> — Payment terms (50% deposit, balance on completion), warranty info, what's NOT included

Use HTML tags: <h2>, <table>, <tr>, <th>, <td>, <p>, <ul>, <li>, <strong>. Make the table use border="1" cellpadding="8" style="border-collapse:collapse;width:100%".
Keep costs realistic for the ${client.industry} industry in Michigan.`;

    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${LOVABLE_API_KEY}` },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-lite", 
        messages: [{ role: "user", content: prompt }] }) });

    const aiData = await aiResponse.json();
    const estimateHtml = aiData?.choices?.[0]?.message?.content || "Estimate generation failed.";

    const today = new Date().toLocaleDateString("en-US", {
      month: "long", day: "numeric", year: "numeric" });

    const fullEmailHtml = `
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: Arial, sans-serif; color: #1e293b; max-width: 750px; margin: 0 auto; padding: 20px; }
  h1 { color: #e8621a; }
  h2 { color: #1e293b; margin-top: 24px; }
  table { margin: 16px 0; }
  th { background: #1e293b; color: white; text-align: left; }
  td { vertical-align: top; }
  .header { border-bottom: 3px solid #e8621a; padding-bottom: 15px; margin-bottom: 20px; }
  .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 13px; color: #666; }
  .validity { background: #fff7ed; border: 1px solid #e8621a; padding: 12px; margin: 20px 0; border-radius: 4px; }
</style></head>
<body>
  <div class="header">
    <h1>${client.business_name}</h1>
    <p><strong>Project Estimate</strong> — ${today}</p>
    <p>Prepared for: <strong>${prospectName}</strong></p>
  </div>
  ${estimateHtml}
  <div class="validity">
    <strong>This estimate is valid for 30 days from ${today}.</strong>
    To proceed, contact ${client.business_name} at ${client.phone || clientEmail}.
  </div>
  <div class="footer">
    <p>${client.business_name} | ${client.city}, ${client.state || "MI"} | ${client.phone || ""}</p>
    <p style="font-size:11px;color:#999;">Estimate generated by M² Performance Training AI Estimate service.</p>
  </div>
</body>
</html>`;

    const subject = `Project Estimate from ${client.business_name} — ${today}`;

    // Send to prospect
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${Deno.env.get("RESEND_API_KEY")}` },
      body: JSON.stringify({
        from: `${client.business_name} <matt@mattmichelstraining.com>`,
        to: [prospectEmail],
        reply_to: clientEmail,
        subject,
        html: fullEmailHtml }) });

    // Send copy to client
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${Deno.env.get("RESEND_API_KEY")}` },
      body: JSON.stringify({
        from: "M² Estimates <matt@mattmichelstraining.com>",
        to: [clientEmail],
        subject: `[Copy] ${subject} — sent to ${prospectName}`,
        html: `<p style="background:#e8f5e9;padding:12px;border-radius:4px;"><strong>✅ This estimate was sent to ${prospectName} (${prospectEmail}).</strong></p>${fullEmailHtml}` }) });

    await supabase
      .from("estimate_generator_clients")
      .update({
        estimate_count: (client.estimate_count || 0) + 1 })
      .eq("id", client.id);

    return new Response(
      JSON.stringify({
        success: true,
        message: `Estimate sent to ${prospectName} at ${prospectEmail} and copy to ${clientEmail}` }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("ai-estimate-generator error:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
