import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    const { data: clients } = await supabase
      .from("handbook_clients")
      .select("*")
      .eq("active", true)
      .limit(50);

    if (!clients?.length) {
      return new Response(JSON.stringify({ message: "No active handbook clients" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY");
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    const FIRECRAWL_API_KEY = Deno.env.get("FIRECRAWL_API_KEY");
    let processed = 0;

    for (const client of clients) {
      try {
        // Scrape state labor law updates
        let laborLawContext = "";
        if (FIRECRAWL_API_KEY) {
          const searchRes = await fetch("https://api.firecrawl.dev/v1/search", {
            method: "POST",
            headers: { Authorization: `Bearer ${FIRECRAWL_API_KEY}`, "Content-Type": "application/json" },
            body: JSON.stringify({
              query: `${client.state || "Michigan"} labor law updates ${client.industry || "small business"} employee handbook requirements ${new Date().getFullYear()}`,
              limit: 5,
              scrapeOptions: { formats: ["markdown"] },
            }),
          });
          const searchData = await searchRes.json();
          if (searchData?.data) {
            laborLawContext = searchData.data.map((r: any) => r.markdown || r.description || "").join("\n\n").slice(0, 4000);
          }
        }

        // Generate handbook sections with AI
        const aiRes = await fetch("https://api.anthropic.com/v1/messages", {
          method: "POST",
          headers: {
            "x-api-key": ANTHROPIC_API_KEY!,
            "content-type": "application/json",
            "anthropic-version": "2023-06-01",
          },
          body: JSON.stringify({
            model: "claude-haiku-4-5-20251001",
            max_tokens: 1200,
            messages: [{
              role: "user",
              content: `Generate an employee handbook update digest for ${client.business_name}, a ${client.industry || "small"} business in ${client.state || "Michigan"} with approximately ${client.employee_count || "10-50"} employees.

Include:
1. Key policy updates needed based on current ${client.state || "Michigan"} labor laws
2. Required notices and postings
3. Anti-harassment and discrimination policy updates
4. PTO/leave policy recommendations
5. Safety and workplace conduct updates

Recent labor law context:
${laborLawContext || "Use general current requirements."}

Format as a clean HTML email with sections, bullet points, and action items. Use professional formatting.`,
            }],
          }),
        });

        const aiData = await aiRes.json();
        const handbookContent = aiData?.content?.[0]?.text || "Unable to generate handbook update.";

        // Send via Resend
        await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            from: "M² Development <matt@notify.m2training.com>",
            to: [client.email],
            subject: `${client.business_name} — Monthly Employee Handbook Update`,
            html: `<div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;background:#1a1a2e;color:#e0e0e0;padding:32px;border-radius:12px;">
              <div style="text-align:center;margin-bottom:24px;">
                <h1 style="color:#e8621a;margin:0;">Employee Handbook Update</h1>
                <p style="color:#888;font-size:13px;">${client.business_name} — ${new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}</p>
              </div>
              ${handbookContent}
              <hr style="border-color:#333;margin:24px 0;">
              <p style="font-size:11px;color:#666;text-align:center;">Generated by M² Development AI Handbook Service<br>Questions? Reply to this email.</p>
            </div>`,
          }),
        });

        await supabase.from("handbook_clients").update({
          last_sent_at: new Date().toISOString(),
          send_count: (client.send_count || 0) + 1,
        }).eq("id", client.id);

        processed++;
      } catch (err) {
        console.error(`Error processing handbook client ${client.id}:`, err);
      }
    }

    return new Response(JSON.stringify({ success: true, processed }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Failed" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
