import { Link } from "react-router-dom";
import { ArrowRight, Phone } from "lucide-react";

interface Service {
  name: string;
  price: string;
  desc: string;
  url: string;
}

interface Category {
  label: string;
  services: Service[];
}

const CATEGORIES: Category[] = [
  {
    label: "Web & Marketing",
    services: [
      { name: "Web Design", price: "from $499", desc: "Custom websites built for local businesses — fast, modern, and conversion-focused.", url: "/get-started" },
      { name: "GBP SaaS (Google Business Posts)", price: "$49–99/mo", desc: "AI posts 3×/week to your Google Business Profile to keep rankings climbing.", url: "/local-marketing" },
      { name: "AI Social Media", price: "$149–299/mo", desc: "Done-for-you Facebook, Instagram, and LinkedIn posts — fully automated.", url: "/social-media-ai" },
      { name: "AI Blog Post Service", price: "$79/mo", desc: "SEO-optimized blog articles written and published on autopilot every month.", url: "/ai-blog-posts" },
      { name: "AI Press Release", price: "$39/mo", desc: "Professional press releases crafted by AI and ready to distribute instantly.", url: "/ai-press-release" },
      { name: "AI Local SEO Pages", price: "$59/mo", desc: "Hyper-local landing pages generated by AI to capture nearby search traffic.", url: "/local-seo-pages" },
      { name: "AI Website Copy Refresh", price: "$49/mo", desc: "Fresh, high-converting copy for your existing website — rewritten monthly.", url: "/ai-website-copy" },
      { name: "AI Ads Copy Generator", price: "$39/mo", desc: "Google and Facebook ad copy that actually converts, generated on demand.", url: "/ai-ads-copy" },
      { name: "AI Social Caption Pack", price: "$29/mo", desc: "30 ready-to-post social captions delivered each month — just copy and paste.", url: "/ai-social-captions" },
      { name: "AI Direct Mail Copy", price: "$49/mo", desc: "Compelling mailer and postcard copy written by AI for offline campaigns.", url: "/direct-mail" },
      { name: "AI Video Script Writer", price: "$39/mo", desc: "Short-form video scripts for Reels, TikTok, and YouTube Shorts on autopilot.", url: "/ai-video-scripts" },
      { name: "Seasonal Promo Planner", price: "$39/mo", desc: "AI-built promotional calendar with copy and ideas for every season.", url: "/promo-planner" },
    ],
  },
  {
    label: "SMS & Phone",
    services: [
      { name: "Missed Call Text-Back", price: "$99/mo", desc: "Instantly texts anyone who calls and gets no answer — never lose a lead again.", url: "/missed-call-saas" },
      { name: "AI Phone Answering", price: "$149/mo", desc: "An AI voice agent answers your phone 24/7 and captures caller information.", url: "/ai-phone-answering" },
      { name: "Text Message Marketing", price: "$79/mo", desc: "Automated SMS campaigns that drive repeat business and referrals.", url: "/text-message-marketing" },
      { name: "Review Request SMS", price: "$39/mo", desc: "Auto-sends a friendly text after every job asking customers for a Google review.", url: "/review-request-sms" },
      { name: "Quote Follow-Up SMS", price: "$49/mo", desc: "Follows up on open estimates via text so no quote goes cold and forgotten.", url: "/quote-followup-sms" },
      { name: "Win-Back SMS", price: "$49/mo", desc: "Re-engages past customers who haven't booked in 90+ days with a smart text.", url: "/winback-sms" },
      { name: "Holiday SMS Blast", price: "$39/mo", desc: "Seasonal holiday texts that keep your brand top-of-mind year-round.", url: "/holiday-sms" },
      { name: "Appointment Reminder SMS", price: "$39/mo", desc: "Automated reminder texts that slash no-shows and last-minute cancellations.", url: "/appointment-reminders" },
      { name: "Speed-to-Lead SMS", price: "$39/mo", desc: "Texts new leads within 60 seconds of inquiry — before your competitors call.", url: "/speed-to-lead" },
      { name: "AI Thank You Text", price: "$19/mo", desc: "Sends a personalized thank-you text after every completed job automatically.", url: "/thank-you-sms" },
      { name: "Warranty Reminder SMS", price: "$29/mo", desc: "Reminds customers when their service warranty is coming up for renewal.", url: "/warranty-reminders" },
      { name: "Satisfaction Survey SMS", price: "$29/mo", desc: "One-tap satisfaction surveys sent post-job to capture feedback effortlessly.", url: "/satisfaction-survey" },
    ],
  },
  {
    label: "Reputation & Reviews",
    services: [
      { name: "AI Reputation Dashboard", price: "$79/mo", desc: "Monitor and manage your online reviews across Google and Facebook in one place.", url: "/ai-reputation" },
      { name: "Google Review Auto-Responder", price: "$49/mo", desc: "AI writes and posts thoughtful responses to every Google review automatically.", url: "/review-responder" },
      { name: "Review Alert SMS", price: "$19/mo", desc: "Texts you the moment a new review lands so you never miss one.", url: "/review-alerts" },
      { name: "AI Google Q&A Manager", price: "$29/mo", desc: "Automatically answers questions posted on your Google Business Profile.", url: "/google-qa" },
      { name: "AI Competitor Watch", price: "$69/mo", desc: "Tracks competitor reviews and rankings so you can stay one step ahead.", url: "/competitor-watch" },
    ],
  },
  {
    label: "AI Content & Tools",
    services: [
      { name: "AI Proposal Generator", price: "$49/mo", desc: "Generates polished, professional proposals in seconds from a simple job brief.", url: "/ai-proposal" },
      { name: "AI Estimate Generator", price: "$49/mo", desc: "Produces detailed project estimates instantly — branded and ready to send.", url: "/ai-estimates" },
      { name: "AI Hiring Assistant", price: "$49/mo", desc: "Writes job postings, screens applicants, and drafts interview questions for you.", url: "/hiring-assistant" },
      { name: "AI Sales Script Generator", price: "$29/mo", desc: "Custom sales scripts built around your services and local market.", url: "/sales-scripts" },
      { name: "AI Weekly Business Digest", price: "$29/mo", desc: "A personalized weekly email summary of your key business metrics and tips.", url: "/weekly-business-digest" },
      { name: "Business KPI Weekly Email", price: "$49/mo", desc: "Auto-pulls your numbers and delivers a clean KPI report to your inbox weekly.", url: "/kpi-email" },
      { name: "Staff Internal Newsletter", price: "$29/mo", desc: "AI-written internal newsletter that keeps your team informed and motivated.", url: "/staff-newsletter" },
    ],
  },
  {
    label: "Marketing Automation",
    services: [
      { name: "AI Email Welcome Drip", price: "$49/mo", desc: "Automated welcome email sequence that nurtures new leads into paying customers.", url: "/welcome-drip" },
      { name: "AI Customer Reactivation", price: "$39/mo", desc: "Wins back dormant customers with a smart 3-part reactivation email campaign.", url: "/reactivation-emails" },
      { name: "Late Payment Chaser", price: "$29/mo", desc: "Politely follows up on unpaid invoices via email so you don't have to.", url: "/payment-chaser" },
    ],
  },
  {
    label: "Lead Gen & B2B",
    services: [
      { name: "Contractor Lead Gen", price: "$399/mo", desc: "Exclusive, local contractor leads delivered directly to your inbox every day.", url: "/contractor-leads" },
      { name: "B2B Dental Database", price: "$49/mo", desc: "Full Michigan dental office contact list — updated monthly and ready to dial.", url: "/b2b-leads" },
      { name: "Field Rep AI Tools", price: "$29/mo", desc: "4 Claude-powered tools built specifically for B2B field sales reps.", url: "/field-rep-tools" },
      { name: "Contractor Chatbot", price: "$149/mo", desc: "24/7 AI chatbot on your website that captures and qualifies contractor leads.", url: "/contractor-chatbot" },
      { name: "Field Rep Weekly Newsletter", price: "Free", desc: "Weekly B2B sales tips and affiliate tool spotlights for field reps.", url: "/newsletter" },
    ],
  },
  {
    label: "Training & Services",
    services: [
      { name: "Web Design Services", price: "Custom", desc: "Full-service web design for local businesses, manufacturers, and real estate pros.", url: "/web-design-services" },
      { name: "SEO Audit Report", price: "$29/mo", desc: "Monthly automated SEO audit report showing exactly what to fix and why.", url: "/seo-reports" },
    ],
  },
];

const TOTAL_SERVICES = CATEGORIES.reduce((sum, cat) => sum + cat.services.length, 0);

export default function AllServices() {
  return (
    <div className="min-h-screen bg-slate-900 text-white">
      {/* Hero */}
      <section className="bg-slate-900 border-b border-slate-800 py-16 px-4 text-center">
        <div className="max-w-3xl mx-auto">
          <div className="inline-block bg-orange-500/10 border border-orange-500/30 rounded-full px-4 py-1 text-orange-400 text-sm font-medium mb-6">
            All {TOTAL_SERVICES} Services
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold text-white mb-4 leading-tight">
            {TOTAL_SERVICES} done-for-you services.<br />
            <span className="text-orange-500">Pick one. Everything runs itself.</span>
          </h1>
          <p className="text-slate-400 text-lg mb-8 max-w-xl mx-auto">
            Every service below is fully automated — set it up once and it works around the clock. No ongoing work required on your end.
          </p>
          <a
            href="tel:3138064952"
            className="inline-flex items-center gap-2 bg-orange-500 hover:bg-orange-600 transition-colors text-white font-semibold px-6 py-3 rounded-lg text-base"
          >
            <Phone className="w-4 h-4" />
            (313) 806-4952 — Text or call Matt
          </a>
        </div>
      </section>

      {/* Categories */}
      <main className="max-w-7xl mx-auto px-4 py-14 space-y-14">
        {CATEGORIES.map((cat) => (
          <section key={cat.label}>
            <div className="flex items-center gap-3 mb-6">
              <h2 className="text-xl font-bold text-white uppercase tracking-wider">
                {cat.label}
              </h2>
              <span className="bg-slate-800 text-slate-400 text-xs font-medium px-2.5 py-1 rounded-full">
                {cat.services.length}
              </span>
              <div className="flex-1 h-px bg-slate-800" />
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {cat.services.map((svc) => (
                <div
                  key={svc.name}
                  className="bg-slate-800 border border-slate-700 rounded-xl p-5 flex flex-col gap-3 hover:border-orange-500/50 hover:bg-slate-800/80 transition-all border-l-4 border-l-orange-500"
                >
                  <div>
                    <h3 className="text-white font-bold text-base leading-snug">{svc.name}</h3>
                    <p className="text-orange-400 font-semibold text-sm mt-1">{svc.price}</p>
                  </div>
                  <p className="text-slate-400 text-sm flex-1">{svc.desc}</p>
                  <Link
                    to={svc.url}
                    className="inline-flex items-center gap-1.5 text-orange-400 hover:text-orange-300 text-sm font-medium transition-colors mt-auto"
                  >
                    Get Started <ArrowRight className="w-4 h-4" />
                  </Link>
                </div>
              ))}
            </div>
          </section>
        ))}
      </main>

      {/* Footer CTA */}
      <section className="bg-slate-800 border-t border-slate-700 py-12 px-4 text-center">
        <div className="max-w-xl mx-auto">
          <h2 className="text-2xl font-bold text-white mb-3">Not sure where to start?</h2>
          <p className="text-slate-400 mb-6">
            Text Matt directly and he'll point you to the right service for your business.
          </p>
          <a
            href="sms:3138064952"
            className="inline-flex items-center gap-2 bg-orange-500 hover:bg-orange-600 transition-colors text-white font-bold px-8 py-3 rounded-lg text-lg"
          >
            <Phone className="w-5 h-5" />
            Text Matt at (313) 806-4952
          </a>
        </div>
      </section>
    </div>
  );
}
