export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white text-slate-800 px-6 py-16 max-w-3xl mx-auto">
      <h1 className="text-3xl font-black mb-2">Terms of Service</h1>
      <p className="text-slate-500 text-sm mb-10">Last updated: March 30, 2026</p>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">1. Agreement</h2>
        <p className="leading-relaxed text-slate-700">
          By using any service offered by M2 Development ("we," "us," "our") at mattmichelstraining.com or related domains, you agree to these Terms of Service. If you do not agree, do not use our services.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">2. Services</h2>
        <p className="leading-relaxed text-slate-700">
          We offer subscription-based and one-time digital services including but not limited to: AI-powered marketing tools, SMS marketing, lead generation, web design, newsletter services, GBP automation, and related business services. Service details are described on each product page.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">3. Payments & Subscriptions</h2>
        <ul className="list-disc pl-6 space-y-2 text-slate-700 leading-relaxed">
          <li>Subscription fees are billed monthly through Stripe.</li>
          <li>Subscriptions auto-renew unless cancelled before the billing date.</li>
          <li>You may cancel at any time; access continues through the end of the paid period.</li>
          <li>We reserve the right to change pricing with 30 days notice.</li>
          <li>All sales are final unless otherwise stated. No refunds on completed one-time services.</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">4. SMS Messaging Terms</h2>
        <p className="leading-relaxed text-slate-700 mb-3">
          By providing your phone number and consenting to SMS communications, you agree to receive automated text messages from M2 Development. This includes service notifications, marketing messages, and transactional alerts.
        </p>
        <ul className="list-disc pl-6 space-y-2 text-slate-700 leading-relaxed">
          <li>You represent that you are the authorized user of the phone number provided.</li>
          <li>Message frequency varies by service. Message and data rates may apply.</li>
          <li>Reply <strong>STOP</strong> to cancel. Reply <strong>HELP</strong> for help.</li>
          <li>Opting out of SMS will not affect other services you have subscribed to.</li>
          <li>We do not use SMS for spam. All messages are related to services you have opted into.</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">5. Acceptable Use</h2>
        <p className="leading-relaxed text-slate-700 mb-3">You agree not to:</p>
        <ul className="list-disc pl-6 space-y-2 text-slate-700 leading-relaxed">
          <li>Use our services for any unlawful purpose</li>
          <li>Resell or redistribute our services without written permission</li>
          <li>Attempt to reverse-engineer or copy our software or AI prompts</li>
          <li>Submit false or misleading information</li>
          <li>Use our SMS or email delivery infrastructure to send unsolicited messages</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">6. AI-Generated Content</h2>
        <p className="leading-relaxed text-slate-700">
          Some services use AI to generate content such as blog posts, ad copy, scripts, and social media posts. AI-generated content is provided as-is. You are responsible for reviewing and approving any content before publishing or distribution. We make no warranties about the accuracy, completeness, or fitness of AI-generated content for any particular purpose.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">7. Intellectual Property</h2>
        <p className="leading-relaxed text-slate-700">
          Content generated by our services on your behalf is owned by you. Our platform, code, prompts, and brand assets remain the property of M2 Development.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">8. Limitation of Liability</h2>
        <p className="leading-relaxed text-slate-700">
          To the maximum extent permitted by law, M² Performance Training is not liable for any indirect, incidental, or consequential damages arising from your use of our services. Our total liability to you shall not exceed the amount you paid us in the 30 days prior to the claim.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">9. Disclaimer of Warranties</h2>
        <p className="leading-relaxed text-slate-700">
          Services are provided "as is" without warranty of any kind. We do not guarantee specific results from lead generation, marketing, or AI services. Business outcomes vary and depend on factors outside our control.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">10. Termination</h2>
        <p className="leading-relaxed text-slate-700">
          We reserve the right to suspend or terminate your access for violation of these terms, non-payment, or any other reason at our discretion, with or without notice.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">11. Governing Law</h2>
        <p className="leading-relaxed text-slate-700">
          These terms are governed by the laws of the State of Michigan. Any disputes shall be resolved in the courts of Wayne County, Michigan.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">12. Changes to Terms</h2>
        <p className="leading-relaxed text-slate-700">
          We may update these terms at any time. Continued use of our services after changes are posted constitutes acceptance of the new terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">13. Contact</h2>
        <p className="leading-relaxed text-slate-700">
          Matt Michels — M² Performance Training<br />
          Grosse Pointe, MI<br />
          matt@mattmichelstraining.com<br />
          (313) 806-4952
        </p>
      </section>
    </div>
  );
}
