import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Loader2, Dumbbell, BookOpen, ChevronDown, ChevronUp, Trash2, Sparkles, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { useState } from "react";
import { toast } from "sonner";
import ConfirmActionModal from "@/components/shared/ConfirmActionModal";

interface AdminUserLibraryProps {
  userId: string;
}

const AdminUserLibrary = ({ userId }: AdminUserLibraryProps) => {
  const queryClient = useQueryClient();
  const [expandedWorkout, setExpandedWorkout] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [confirmDelete, setConfirmDelete] = useState<{ id: string; table: string; label: string } | null>(null);

  // AI generate state
  const [showGenerate, setShowGenerate] = useState(false);
  const [genPrompt, setGenPrompt] = useState("");
  const [generating, setGenerating] = useState(false);

  const { data: communityWorkouts = [], isLoading: loadingWorkouts } = useQuery({
    queryKey: ["admin-user-workouts", userId],
    queryFn: async () => {
      const { data } = await supabase
        .from("community_workouts")
        .select("id, title, creator_name, exercises, created_at, is_public, source_type")
        .eq("user_id", userId)
        .order("created_at", { ascending: false });
      return data || [];
    },
  });

  const { data: activePrograms = [], isLoading: loadingActive } = useQuery({
    queryKey: ["admin-user-active-programs", userId],
    queryFn: async () => {
      const { data } = await supabase
        .from("user_active_programs")
        .select("id, program_id, start_date, status, training_programs(title, category, sport, total_weeks)")
        .eq("user_id", userId)
        .order("created_at", { ascending: false });
      return (data || []) as any[];
    },
  });

  const { data: purchasedPrograms = [], isLoading: loadingPurchased } = useQuery({
    queryKey: ["admin-user-purchased-programs", userId],
    queryFn: async () => {
      const { data } = await supabase
        .from("purchased_programs" as any)
        .select("id, program_title, program_type, sport, exercises, purchased_at, is_active")
        .eq("user_id", userId)
        .order("purchased_at", { ascending: false });
      return (data || []) as any[];
    },
  });

  const loading = loadingWorkouts || loadingActive || loadingPurchased;

  const invalidateAll = () => {
    queryClient.invalidateQueries({ queryKey: ["admin-user-workouts", userId] });
    queryClient.invalidateQueries({ queryKey: ["admin-user-active-programs", userId] });
    queryClient.invalidateQueries({ queryKey: ["admin-user-purchased-programs", userId] });
  };

  /** Generate a workout via ai-workout-suggest and insert into user's library */
  const handleGenerate = async () => {
    if (!genPrompt.trim()) {
      toast.error("Enter a description for the workout");
      return;
    }
    setGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke("ai-workout-suggest", {
        body: {
          mode: "dual-path",
          path: "workout",
          userText: genPrompt.trim(),
        },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      // Insert into user's library
      const { error: saveErr } = await supabase
        .from("community_workouts")
        .insert({
          user_id: userId,
          title: data.title || "Custom Workout",
          description: data.description || "Generated by Coach Matt",
          creator_name: "Coach Matt",
          is_public: false,
          exercises: data.exercises || [],
          source_type: "coach_seeded",
        });
      if (saveErr) throw saveErr;

      // Notify the user
      await supabase.from("notifications").insert({
        user_id: userId,
        type: "new_workout",
        title: "New Workout Added!",
        body: `Coach Matt added "${data.title}" to your Workouts.`,
        link: "/dashboard",
      });

      toast.success(`"${data.title}" added to athlete's library`);
      setGenPrompt("");
      setShowGenerate(false);
      invalidateAll();
    } catch (e: any) {
      toast.error(e.message || "Generation failed");
    } finally {
      setGenerating(false);
    }
  };

  /** Execute confirmed delete */
  const executeDelete = async () => {
    if (!confirmDelete) return;
    setDeletingId(confirmDelete.id);
    try {
      const { error } = await supabase
        .from(confirmDelete.table as any)
        .delete()
        .eq("id", confirmDelete.id);
      if (error) throw error;
      toast.success(`Removed "${confirmDelete.label}" from library`);
      invalidateAll();
    } catch (e: any) {
      toast.error(e.message || "Delete failed");
    } finally {
      setDeletingId(null);
      setConfirmDelete(null);
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center py-4">
        <Loader2 size={16} className="text-primary animate-spin" />
      </div>
    );
  }

  const hasNothing = communityWorkouts.length === 0 && activePrograms.length === 0 && purchasedPrograms.length === 0;

  return (
    <div className="space-y-3">
      {/* AI Generate Button */}
      {!showGenerate ? (
        <button
          onClick={() => setShowGenerate(true)}
          className="w-full flex items-center justify-center gap-1.5 py-2 border border-dashed border-primary/40 text-primary text-[10px] font-bold uppercase tracking-widest hover:bg-primary/5 transition-colors"
        >
          <Sparkles size={12} /> Generate & Add Workout
        </button>
      ) : (
        <div className="bg-secondary/20 border border-border p-3 space-y-2">
          <p className="text-[10px] font-bold uppercase tracking-widest text-primary">
            AI Workout Generator
          </p>
          <Textarea
            value={genPrompt}
            onChange={(e) => setGenPrompt(e.target.value)}
            placeholder="e.g., Build a 3-day upper/lower split for a 16yo football player with full gym access. Focus on explosiveness."
            className="text-xs min-h-[60px]"
          />
          <div className="flex gap-2">
            <button
              onClick={handleGenerate}
              disabled={generating || !genPrompt.trim()}
              className="flex items-center gap-1.5 px-4 py-2 bg-primary text-primary-foreground text-[10px] font-bold uppercase tracking-widest hover:opacity-90 transition-all disabled:opacity-50"
            >
              {generating ? <Loader2 size={12} className="animate-spin" /> : <Sparkles size={12} />}
              {generating ? "Generating…" : "Generate & Add"}
            </button>
            <button
              onClick={() => { setShowGenerate(false); setGenPrompt(""); }}
              className="px-3 py-2 text-[10px] font-bold uppercase tracking-widest text-muted-foreground hover:text-foreground transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {hasNothing && !showGenerate && (
        <p className="text-xs text-muted-foreground">No workouts or programs in library.</p>
      )}

      {/* Interactive Programs */}
      {activePrograms.length > 0 && (
        <div>
          <p className="text-[9px] font-bold uppercase tracking-widest text-primary mb-1.5 flex items-center gap-1">
            <BookOpen size={10} /> Interactive Programs ({activePrograms.length})
          </p>
          <div className="space-y-1">
            {activePrograms.map((ap: any) => (
              <div key={ap.id} className="bg-card border border-border p-2 flex items-center justify-between group">
                <div className="min-w-0 flex-1">
                  <p className="text-xs font-bold text-foreground truncate">{ap.training_programs?.title || "Unknown"}</p>
                  <p className="text-[10px] text-muted-foreground">
                    {ap.training_programs?.category}{ap.training_programs?.sport ? ` · ${ap.training_programs.sport}` : ""}
                    {ap.training_programs?.total_weeks ? ` · ${ap.training_programs.total_weeks}wk` : ""}
                  </p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <Badge
                    variant={ap.status === "active" ? "default" : "secondary"}
                    className="text-[8px] uppercase tracking-widest"
                  >
                    {ap.status}
                  </Badge>
                  <button
                    onClick={() => setConfirmDelete({ id: ap.id, table: "user_active_programs", label: ap.training_programs?.title || "program" })}
                    disabled={deletingId === ap.id}
                    className="p-1 text-muted-foreground hover:text-destructive transition-colors opacity-0 group-hover:opacity-100"
                    title="Remove from library"
                  >
                    {deletingId === ap.id ? <Loader2 size={12} className="animate-spin" /> : <Trash2 size={12} />}
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Purchased / Custom Programs */}
      {purchasedPrograms.length > 0 && (
        <div>
          <p className="text-[9px] font-bold uppercase tracking-widest text-primary mb-1.5 flex items-center gap-1">
            <BookOpen size={10} /> Custom Programs ({purchasedPrograms.length})
          </p>
          <div className="space-y-1">
            {purchasedPrograms.map((pp: any) => {
              const exercises = Array.isArray(pp.exercises) ? pp.exercises : [];
              return (
                <div key={pp.id} className="bg-card border border-border p-2 group">
                  <div className="flex items-center justify-between">
                    <div className="min-w-0 flex-1">
                      <p className="text-xs font-bold text-foreground truncate">{pp.program_title}</p>
                      <p className="text-[10px] text-muted-foreground">
                        {pp.program_type}{pp.sport ? ` · ${pp.sport}` : ""} · {exercises.length} exercises
                      </p>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <Badge
                        variant={pp.is_active ? "default" : "secondary"}
                        className="text-[8px] uppercase tracking-widest"
                      >
                        {pp.is_active ? "active" : "past"}
                      </Badge>
                      <button
                        onClick={() => setConfirmDelete({ id: pp.id, table: "purchased_programs", label: pp.program_title })}
                        disabled={deletingId === pp.id}
                        className="p-1 text-muted-foreground hover:text-destructive transition-colors opacity-0 group-hover:opacity-100"
                        title="Remove from library"
                      >
                        {deletingId === pp.id ? <Loader2 size={12} className="animate-spin" /> : <Trash2 size={12} />}
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Community Workouts */}
      {communityWorkouts.length > 0 && (
        <div>
          <p className="text-[9px] font-bold uppercase tracking-widest text-primary mb-1.5 flex items-center gap-1">
            <Dumbbell size={10} /> Saved Workouts ({communityWorkouts.length})
          </p>
          <div className="space-y-1">
            {communityWorkouts.map((w: any) => {
              const exercises = Array.isArray(w.exercises) ? w.exercises : [];
              const isExpanded = expandedWorkout === w.id;
              return (
                <div key={w.id} className="bg-card border border-border group">
                  <div className="flex items-center">
                    <button
                      onClick={() => setExpandedWorkout(isExpanded ? null : w.id)}
                      className="flex-1 text-left p-2 flex items-center justify-between hover:bg-accent/20 transition-colors min-w-0"
                    >
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-1.5">
                          <p className="text-xs font-bold text-foreground truncate">{w.title}</p>
                          {!w.is_public && (
                            <Badge variant="outline" className="text-[7px] px-1 py-0">Private</Badge>
                          )}
                        </div>
                        <p className="text-[10px] text-muted-foreground">
                          by {w.creator_name} · {exercises.length} exercises · {new Date(w.created_at).toLocaleDateString()}
                        </p>
                      </div>
                      {isExpanded ? <ChevronUp size={12} className="text-muted-foreground shrink-0" /> : <ChevronDown size={12} className="text-muted-foreground shrink-0" />}
                    </button>
                    <button
                      onClick={() => setConfirmDelete({ id: w.id, table: "community_workouts", label: w.title })}
                      disabled={deletingId === w.id}
                      className="p-2 text-muted-foreground hover:text-destructive transition-colors opacity-0 group-hover:opacity-100 shrink-0"
                      title="Remove from library"
                    >
                      {deletingId === w.id ? <Loader2 size={12} className="animate-spin" /> : <Trash2 size={12} />}
                    </button>
                  </div>
                  {isExpanded && exercises.length > 0 && (
                    <div className="border-t border-border px-3 py-2 space-y-1">
                      {exercises.map((ex: any, i: number) => (
                        <div key={i} className="flex items-center gap-2 text-[11px]">
                          <span className="text-muted-foreground font-mono w-4 text-right">{i + 1}.</span>
                          <span className="font-bold text-foreground flex-1 truncate">{ex.title || ex.name}</span>
                          <span className="font-mono text-primary shrink-0">{ex.sets || "3"}×{ex.reps || "10"}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      <ConfirmActionModal
        open={!!confirmDelete}
        onOpenChange={(open) => { if (!open) setConfirmDelete(null); }}
        title="Remove from Library"
        description={`Are you sure you want to remove "${confirmDelete?.label}" from this athlete's library? This cannot be undone.`}
        confirmLabel="Remove"
        onConfirm={executeDelete}
      />
    </div>
  );
};

export default AdminUserLibrary;
