// GR-20: Weekly client-branded PDF report (returns HTML for browser print-to-PDF)
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };
const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const { client_id, business_name } = await req.json().catch(() => ({}));
    const since = new Date(Date.now() - 7 * 86400_000).toISOString();

    const { data: signals } = await supabase
      .from("growth_radar_signals" as any)
      .select("*")
      .gte("detected_at", since)
      .gte("confidence", 7)
      .order("confidence", { ascending: false })
      .limit(25);

    const rows = ((signals as any[]) || [])
      .map(
        (s) => `<tr>
          <td style="padding:10px;border-bottom:1px solid #1f2937;"><strong>${s.company_name}</strong><br/><span style="color:#64748b;font-size:11px">${s.county || "MI"} · ${s.signal_type}</span></td>
          <td style="padding:10px;border-bottom:1px solid #1f2937;color:#22d3ee;font-weight:bold;text-align:center">${s.confidence}/10</td>
          <td style="padding:10px;border-bottom:1px solid #1f2937;color:#cbd5e1;font-size:12px">${(s.recommended_pitch || "").slice(0, 200)}</td>
        </tr>`
      )
      .join("");

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Growth Radar Weekly Report</title>
<style>body{font-family:-apple-system,sans-serif;background:#0a1628;color:#e2e8f0;padding:40px;max-width:900px;margin:0 auto}
h1{color:#22d3ee;border-bottom:2px solid #22d3ee;padding-bottom:10px}
table{width:100%;border-collapse:collapse;margin-top:20px;background:#0f1e35;border-radius:8px;overflow:hidden}
th{background:#1e3a5f;color:#22d3ee;padding:12px;text-align:left;font-size:12px;text-transform:uppercase}
.hero{background:linear-gradient(135deg,#0e7490,#155e75);padding:24px;border-radius:8px;margin-bottom:24px}
@media print{body{background:white;color:black}h1{color:#0e7490}.hero{background:#0e7490;color:white}}
</style></head><body>
<div class="hero">
  <h1 style="margin:0;border:none;color:white">Growth Radar — Weekly Intelligence</h1>
  <p style="margin:8px 0 0 0;opacity:0.9">Prepared for ${business_name || "your team"} · Week of ${new Date().toLocaleDateString()}</p>
</div>
<p style="color:#94a3b8">${(signals || []).length} qualified expansion signals (confidence ≥ 7) detected across Michigan.</p>
<table>
  <thead><tr><th>Company / Type</th><th style="text-align:center">Confidence</th><th>Recommended Approach</th></tr></thead>
  <tbody>${rows || '<tr><td colspan="3" style="padding:24px;text-align:center;color:#64748b">No signals this week. Check back next Monday.</td></tr>'}</tbody>
</table>
<p style="color:#64748b;font-size:11px;margin-top:40px;text-align:center">Generated by Detroit Web Agency · Growth Radar · detroitwebagent.com</p>
<script>setTimeout(()=>window.print(),500)</script>
</body></html>`;

    return new Response(html, { headers: { ...corsHeaders, "Content-Type": "text/html" } });
  } catch (e) {
    return new Response(JSON.stringify({ error: String(e) }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
