import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY") || "";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };


const EMAIL_SIGNATURE = `<div style="margin-top:24px;padding-top:16px;border-top:1px solid #334155;display:flex;align-items:center;gap:12px;"><img src="https://www.mattmichelstraining.com/images/matt-boat.jpg" alt="Matt Michels" style="width:48px;height:48px;border-radius:50%;object-fit:cover;" /><div style="font-size:13px;color:#94a3b8;"><strong style="color:#e2e8f0;">Matt Michels</strong><br/>Grosse Pointe, MI · (313) 806-4952</div><img src="https://www.mattmichelstraining.com/images/m2-development-logo.png" alt="M2 Development" style="width:36px;height:36px;margin-left:auto;object-fit:contain;" /></div>`;

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: clients, error: clientsError } = await supabase
      .from("video_script_clients")
      .select("*")
      .eq("active", true);

    if (clientsError) throw clientsError;
    if (!clients || clients.length === 0) {
      return new Response(JSON.stringify({ message: "No active clients" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    let processed = 0;

    for (const client of clients) {
      const prompt = `You are a viral short-form video content strategist. Write 8 short video scripts for a ${client.industry} business called "${client.business_name}" in ${client.city}, ${client.state || "MI"}.

Each script should be:
- 25-35 seconds when spoken aloud
- Designed for TikTok and Instagram Reels
- Include a hook in the first 3 seconds
- Have a clear call-to-action at the end
- Mix educational, entertaining, and promotional content

Format each script as:
<strong>Script [number]: [Title]</strong>
<em>Hook:</em> [Opening line]
<em>Body:</em> [Main content]
<em>CTA:</em> [Call to action]
<em>On-screen text suggestion:</em> [Text overlay idea]

Use HTML formatting with <ol>, <li>, <strong>, <em>, <p> tags.`;

      const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${LOVABLE_API_KEY}` },
        body: JSON.stringify({
          model: "google/gemini-2.5-flash-lite", 
          messages: [{ role: "user", content: prompt }] }) });

      const aiData = await aiResponse.json();
      const scriptsHtml = aiData?.choices?.[0]?.message?.content || "Script generation failed.";

      const monthName = new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" });

      const emailHtml = `
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: Arial, sans-serif; color: #1e293b; max-width: 700px; margin: 0 auto; padding: 20px; }
  h1 { color: #e8621a; border-bottom: 2px solid #e8621a; padding-bottom: 10px; }
  h2 { color: #1e293b; }
  strong { color: #e8621a; }
  em { color: #555; }
  li { margin-bottom: 16px; padding-bottom: 16px; border-bottom: 1px solid #eee; }
  .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 13px; color: #666; }
  .tip { background: #fff7ed; border-left: 4px solid #e8621a; padding: 12px; margin: 20px 0; }
</style></head>
<body>
  <h1>🎬 Your ${monthName} Video Scripts</h1>
  <p>Hi ${client.contact_name || "there"}! Here are 8 fresh video scripts for ${client.business_name}.</p>
  <div class="tip">
    <strong>Pro tip:</strong> Film 2 scripts per week. Batch-film all 8 in one session for efficiency. Use trending audio when possible!
  </div>
  ${scriptsHtml}
  <div class="footer">
    <p>Generated by M² Performance Training's AI Video Script service.</p>
    <p>Questions? Reply to this email or text Matt at (313) 806-4952.</p>
  </div>
</body>
</html>`;

      const emailRes = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${Deno.env.get("RESEND_API_KEY")}` },
        body: JSON.stringify({
          from: "M² Video Scripts <matt@mattmichelstraining.com>",
          to: [client.email], bcc: ["matthewmichels4@gmail.com"],
          subject: `Your ${monthName} Video Scripts — ${client.business_name} (8 Ready to Film)`,
          html: emailHtml}) });

      if (!emailRes.ok) {
        console.error(`Failed to email ${client.email}:`, await emailRes.text());
        continue;
      }

      await supabase
        .from("video_script_clients")
        .update({
          script_count: (client.script_count || 0) + 8,
          last_sent_at: new Date().toISOString() })
        .eq("id", client.id);

      processed++;
    }

    return new Response(
      JSON.stringify({ success: true, processed }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("ai-video-script-writer error:", error);
    return new Response(
      JSON.stringify({ error: (error instanceof Error ? error.message : "Unknown error") }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
