// meta-ads-poster — creates Meta ad campaigns from ad-creative-studio images
//
// Takes ad creative images (already generated by ad-creative-studio) and:
// 1. Uploads them to Meta's ad image library
// 2. Creates Campaign → Ad Set → Ad Creative → Ad (all PAUSED by default)
// 3. Returns all created IDs + Ads Manager deep-link
//
// Required Supabase secrets (secondary project zmyczlfuufhngzovkjdh):
//   META_USER_ACCESS_TOKEN  — from M2 Api Dev app (Development mode, ads_management)
//   META_AD_ACCOUNT_ID      — "act_1969872620513768" (M2ads)
//
// Called with:
//   POST {"jobId":"...","pageId":"...","niche":"nurse","dailyBudgetCents":500}
//   POST {"jobId":"...","pageId":"...","dryRun":true}  ← validates + returns plan, no API calls
//   POST {"listPages":true}  ← returns all Pages the token has access to
//   POST {"jobId":"...","pageId":"...","brandSlug":"dwa","dailyBudgetCents":500}  ← DWA brand

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const log = (step: string, data?: unknown) =>
  console.log(`[META-POSTER] ${step}${data ? " — " + JSON.stringify(data) : ""}`);

const META = "https://graph.facebook.com/v21.0";

// ── Image upload to Meta ───────────────────────────────────────────────────────
async function uploadImageToMeta(
  imageUrl: string,
  name: string,
  adAccount: string,
  token: string
): Promise<string> {
  // Fetch image bytes from Supabase Storage
  const imgRes = await fetch(imageUrl, { signal: AbortSignal.timeout(30_000) });
  if (!imgRes.ok) throw new Error(`Failed to fetch image: ${imgRes.status} ${imageUrl}`);

  const imgBytes = new Uint8Array(await imgRes.arrayBuffer());
  // Chunked encoding avoids call-stack overflow on large images
  let base64 = "";
  for (let i = 0; i < imgBytes.length; i += 8192) {
    base64 += String.fromCharCode(...imgBytes.subarray(i, i + 8192));
  }
  base64 = btoa(base64);

  log("Uploading image to Meta", { name, bytes: imgBytes.byteLength });

  const uploadRes = await fetch(`${META}/${adAccount}/adimages`, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ bytes: base64, name }),
  });

  const uploadData = await uploadRes.json();
  if (uploadData.error) throw new Error(`Meta image upload failed: ${uploadData.error.message}`);

  // Response: { images: { "filename.jpg": { hash, url, ... } } }
  const images = uploadData.images ?? {};
  const firstKey = Object.keys(images)[0];
  if (!firstKey) throw new Error("No image hash returned from Meta");

  const hash = images[firstKey].hash;
  log("Image uploaded", { hash });
  return hash;
}

// ── Create campaign ────────────────────────────────────────────────────────────
async function createCampaign(
  adAccount: string,
  name: string,
  objective: string,
  token: string
): Promise<string> {
  const res = await fetch(`${META}/${adAccount}/campaigns`, {
    method: "POST",
    headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      name,
      objective,
      status: "PAUSED",
      special_ad_categories: [],
      is_adset_budget_sharing_enabled: false,
    }),
  });
  const data = await res.json();
  if (data.error) throw new Error(`Create campaign failed: ${JSON.stringify(data.error)}`);
  log("Campaign created", { id: data.id, name });
  return data.id;
}

// ── Create ad set ──────────────────────────────────────────────────────────────
async function createAdSet(
  adAccount: string,
  campaignId: string,
  name: string,
  dailyBudgetCents: number,
  objective: string,
  token: string,
  instagramActorId?: string
): Promise<string> {
  // Optimization goal depends on campaign objective
  const goalMap: Record<string, { billing_event: string; optimization_goal: string }> = {
    OUTCOME_AWARENESS: { billing_event: "IMPRESSIONS", optimization_goal: "REACH" },
    OUTCOME_TRAFFIC: { billing_event: "LINK_CLICKS", optimization_goal: "LINK_CLICKS" },
    OUTCOME_ENGAGEMENT: { billing_event: "IMPRESSIONS", optimization_goal: "POST_ENGAGEMENT" },
    OUTCOME_LEADS: { billing_event: "IMPRESSIONS", optimization_goal: "LEAD_GENERATION" },
    OUTCOME_SALES: { billing_event: "IMPRESSIONS", optimization_goal: "OFFSITE_CONVERSIONS" },
  };
  const { billing_event, optimization_goal } = goalMap[objective] ?? goalMap.OUTCOME_AWARENESS;

  const res = await fetch(`${META}/${adAccount}/adsets`, {
    method: "POST",
    headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      name,
      campaign_id: campaignId,
      billing_event,
      optimization_goal,
      daily_budget: dailyBudgetCents, // in cents (USD)
      bid_strategy: "LOWEST_COST_WITHOUT_CAP",
      targeting: {
        geo_locations: { countries: ["US"] },
        age_min: 25,
        age_max: 55,
        publisher_platforms: instagramActorId ? ["facebook", "instagram"] : ["facebook"],
        ...(instagramActorId ? {
          facebook_positions: ["feed"],
          instagram_positions: ["stream", "reels"],
        } : {
          facebook_positions: ["feed"],
        }),
        targeting_automation: { advantage_audience: 0 },
      },
      status: "PAUSED",
      // Start immediately (no end date — can be set in Ads Manager)
    }),
  });
  const data = await res.json();
  if (data.error) throw new Error(`Create ad set failed: ${JSON.stringify(data.error)}`);
  log("Ad set created", { id: data.id, name });
  return data.id;
}

// ── Create ad creative (image ad) ─────────────────────────────────────────────
async function createAdCreative(
  adAccount: string,
  pageId: string,
  imageHash: string,
  headline: string,
  body: string,
  linkUrl: string,
  ctaType: string,
  name: string,
  token: string,
  instagramActorId?: string
): Promise<string> {
  const res = await fetch(`${META}/${adAccount}/adcreatives`, {
    method: "POST",
    headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      name,
      object_story_spec: {
        page_id: pageId,
        ...(instagramActorId ? { instagram_actor_id: instagramActorId } : {}),
        link_data: {
          image_hash: imageHash,
          link: linkUrl,
          message: body,
          name: headline, // headline shown under image
          call_to_action: {
            type: ctaType, // LEARN_MORE | SHOP_NOW | SIGN_UP | GET_QUOTE
            value: { link: linkUrl },
          },
        },
      },
    }),
  });
  const data = await res.json();
  if (data.error) throw new Error(`Create creative failed: ${JSON.stringify(data.error)}`);
  log("Creative created", { id: data.id });
  return data.id;
}

// ── Upload video to Meta ───────────────────────────────────────────────────────
async function uploadVideoToMeta(
  videoUrl: string,
  title: string,
  adAccount: string,
  token: string
): Promise<string> {
  // Fetch video bytes from storage
  const vidRes = await fetch(videoUrl, { signal: AbortSignal.timeout(120_000) });
  if (!vidRes.ok) throw new Error(`Failed to fetch video: ${vidRes.status} ${videoUrl}`);

  const vidBytes = new Uint8Array(await vidRes.arrayBuffer());
  log("Video fetched for Meta upload", { bytes: vidBytes.byteLength, title });

  // Multipart upload to Meta
  const form = new FormData();
  form.append("title", title.slice(0, 100));
  form.append("source", new Blob([vidBytes], { type: "video/mp4" }), "ad.mp4");

  const uploadRes = await fetch(`${META}/${adAccount}/advideos`, {
    method: "POST",
    headers: { "Authorization": `Bearer ${token}` },
    body: form,
  });

  const uploadData = await uploadRes.json();
  if (uploadData.error) throw new Error(`Meta video upload failed: ${uploadData.error.message}`);

  const videoId = uploadData.id;
  if (!videoId) throw new Error("No video ID returned from Meta");
  log("Video uploaded to Meta", { videoId });

  // Wait for Meta to process the video (up to 30s)
  for (let i = 0; i < 6; i++) {
    await new Promise((r) => setTimeout(r, 5_000));
    const statusRes = await fetch(`${META}/${videoId}?fields=status&access_token=${token}`, {
      headers: { "Authorization": `Bearer ${token}` },
    });
    const statusData = await statusRes.json();
    const s = statusData.status?.video_status ?? statusData.status;
    log("Video processing status", { status: s, attempt: i + 1 });
    if (s === "ready" || s === "READY") return videoId;
    if (s === "error" || s === "ERROR") throw new Error(`Meta video processing failed: ${JSON.stringify(statusData)}`);
  }

  log("Video status unknown after 30s — proceeding anyway (Meta may still be processing)");
  return videoId;
}

// ── Create video ad creative ───────────────────────────────────────────────────
async function createVideoAdCreative(
  adAccount: string,
  pageId: string,
  videoId: string,
  headline: string,
  body: string,
  linkUrl: string,
  ctaType: string,
  name: string,
  token: string,
  instagramActorId?: string,
  thumbnailUrl?: string
): Promise<string> {
  const res = await fetch(`${META}/${adAccount}/adcreatives`, {
    method: "POST",
    headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      name,
      object_story_spec: {
        page_id: pageId,
        ...(instagramActorId ? { instagram_actor_id: instagramActorId } : {}),
        video_data: {
          video_id: videoId,
          message: body,
          title: headline,
          ...(thumbnailUrl ? { image_url: thumbnailUrl } : {}),
          call_to_action: {
            type: ctaType,
            value: { link: linkUrl },
          },
        },
      },
    }),
  });
  const data = await res.json();
  if (data.error) throw new Error(`Create video creative failed: ${JSON.stringify(data.error)}`);
  log("Video creative created", { id: data.id });
  return data.id;
}

// ── Create ad ─────────────────────────────────────────────────────────────────
async function createAd(
  adAccount: string,
  adSetId: string,
  creativeId: string,
  name: string,
  token: string
): Promise<string> {
  const res = await fetch(`${META}/${adAccount}/ads`, {
    method: "POST",
    headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      name,
      adset_id: adSetId,
      creative: { creative_id: creativeId },
      status: "PAUSED", // always start PAUSED — activate in Ads Manager after review
    }),
  });
  const data = await res.json();
  if (data.error) throw new Error(`Create ad failed: ${JSON.stringify(data.error)}`);
  log("Ad created", { id: data.id });
  return data.id;
}

// ── Per-brand config ──────────────────────────────────────────────────────────
// Confirmed Facebook Page IDs (from Business Manager 2026-05-27/28):
//   m2  → 696307083755196  (Matt Michels Training)
//   dwa → 1043059478901800 (Detroit Web Agency)
//   gng → 1110608005476128 (Guilds and Grains — created 2026-05-28)
//
// Confirmed Instagram Account IDs (from Business Manager 2026-05-28):
//   m2  → 17841405733147321  (@mattmichelstraining)
//   dwa → 17841426666971913  (@dwaagent1 — re-enable instagramActorId after linking to DWA FB page)
const BRAND_CONFIG: Record<string, {
  campaignPrefix: string;
  objective: string;
  ctaType: string;
  linkUrl: string;
  bodyTemplate: string;
  defaultPageId?: string;
  instagramActorId?: string;
  thumbnailUrl?: string; // fallback thumbnail for video ads (required by Meta)
}> = {
  m2: {
    campaignPrefix: "M2 Training",
    defaultPageId: "696307083755196",
    instagramActorId: "17841405733147321",
    objective: "OUTCOME_TRAFFIC",
    ctaType: "LEARN_MORE",
    linkUrl: "https://www.mattmichelstraining.com/start-trial?product=elite&utm_source=meta&utm_medium=paid&utm_campaign=m2_general",
    bodyTemplate: "Transform your fitness with 1-on-1 coaching from Matt Michels. Real results, real accountability. Detroit's top personal trainer.",
  },
  "m2-elite": {
    campaignPrefix: "M2 Elite Training",
    defaultPageId: "696307083755196",
    instagramActorId: "17841405733147321",
    objective: "OUTCOME_LEADS",
    ctaType: "LEARN_MORE",
    linkUrl: "https://www.mattmichelstraining.com/start-trial?product=elite&utm_source=meta&utm_medium=paid&utm_campaign=m2_elite",
    bodyTemplate: "Lose 20+ lbs with 1-on-1 personal training from Matt Michels. $349/mo, cancel anytime. Free 7-day trial. Detroit-area trainer.",
  },
  dwa: {
    campaignPrefix: "Detroit Web Agency",
    defaultPageId: "1043059478901800",
    // instagramActorId: "17841426666971913",  — re-enable after linking @dwaagent1 to DWA Facebook page in Business Manager
    objective: "OUTCOME_TRAFFIC",
    ctaType: "GET_QUOTE",
    linkUrl: "https://detroitwebagent.com/start-here?utm_source=meta&utm_medium=paid&utm_campaign=dwa_general",
    bodyTemplate: "More leads, less effort. Detroit Web Agency builds AI-powered websites that work while you sleep.",
    thumbnailUrl: "https://www.detroitwebagent.com/dwa-og-image.png",
  },
  "dwa-restaurant": {
    campaignPrefix: "DWA Restaurant Websites",
    defaultPageId: "1043059478901800",
    objective: "OUTCOME_LEADS",
    ctaType: "GET_QUOTE",
    linkUrl: "https://detroitwebagent.com/start-here?utm_source=meta&utm_medium=paid&utm_campaign=restaurant_website",
    bodyTemplate: "Detroit restaurant? Get a website that brings in more diners. Free mockup in 24 hours. No contracts. $799 setup + $79/mo.",
    thumbnailUrl: "https://www.detroitwebagent.com/dwa-og-image.png",
  },
  "dwa-website": {
    campaignPrefix: "DWA Website Packages",
    defaultPageId: "1043059478901800",
    objective: "OUTCOME_LEADS",
    ctaType: "GET_QUOTE",
    linkUrl: "https://detroitwebagent.com/start-here?utm_source=meta&utm_medium=paid&utm_campaign=website_packages",
    bodyTemplate: "Detroit business? Your competitors have a great website. You can too. Free mockup in 24 hours. From $499 setup + $49/mo.",
    thumbnailUrl: "https://www.detroitwebagent.com/dwa-og-image.png",
  },
  "dwa-missed-call": {
    campaignPrefix: "DWA Missed-Call Catch",
    defaultPageId: "1043059478901800",
    objective: "OUTCOME_LEADS",
    ctaType: "LEARN_MORE",
    linkUrl: "https://detroitwebagent.com/ad/missed-call?utm_source=meta&utm_medium=paid&utm_campaign=missed_call_factory",
    bodyTemplate: "Every missed call is a missed paycheck. Missed-Call Catch texts them back in 60 seconds — automatically. $99/mo, 7-day free trial.",
    thumbnailUrl: "https://www.detroitwebagent.com/dwa-og-image.png",
  },
  "dwa-dead-leads": {
    campaignPrefix: "DWA Dead Lead Reactivation",
    defaultPageId: "1043059478901800",
    objective: "OUTCOME_LEADS",
    ctaType: "LEARN_MORE",
    linkUrl: "https://detroitwebagent.com/ad/dead-leads?utm_source=meta&utm_medium=paid&utm_campaign=dead_leads_factory",
    bodyTemplate: "Your dead leads are worth real money. We send one targeted message and find the ones ready to buy now. First campaign FREE.",
    thumbnailUrl: "https://www.detroitwebagent.com/dwa-og-image.png",
  },
  "dwa-site-radar": {
    campaignPrefix: "DWA SiteRadar",
    defaultPageId: "1043059478901800",
    objective: "OUTCOME_LEADS",
    ctaType: "LEARN_MORE",
    linkUrl: "https://detroitwebagent.com/ad/site-radar?utm_source=meta&utm_medium=paid&utm_campaign=site_radar_factory",
    bodyTemplate: "See every company that visited your website today — before they call your competitor. SiteRadar. $49/mo, 7-day free trial.",
    thumbnailUrl: "https://www.detroitwebagent.com/dwa-og-image.png",
  },
  "dwa-trade-radar": {
    campaignPrefix: "DWA Trade Radar",
    defaultPageId: "1043059478901800",
    objective: "OUTCOME_LEADS",
    ctaType: "LEARN_MORE",
    linkUrl: "https://detroitwebagent.com/ad/trade-radar?utm_source=meta&utm_medium=paid&utm_campaign=trade_radar_factory",
    bodyTemplate: "Stop paying for shared Angi leads. Trade Radar delivers daily permit pulls and storm damage signals — exclusively yours. $149/mo, free trial.",
    thumbnailUrl: "https://www.detroitwebagent.com/dwa-og-image.png",
  },
  "dwa-ai-phone": {
    campaignPrefix: "DWA AI Phone Answering",
    defaultPageId: "1043059478901800",
    objective: "OUTCOME_LEADS",
    ctaType: "LEARN_MORE",
    linkUrl: "https://detroitwebagent.com/start-here?product=ai_phone&utm_source=meta&utm_medium=paid&utm_campaign=ai_phone_factory",
    bodyTemplate: "While you're on the job, your phone keeps ringing — and losing you customers. AI Phone Answering handles every call, 24/7. $149/mo, free trial.",
    thumbnailUrl: "https://www.detroitwebagent.com/dwa-og-image.png",
  },
  "dwa-contractor-leads": {
    campaignPrefix: "DWA Contractor Leads",
    defaultPageId: "1043059478901800",
    objective: "OUTCOME_LEADS",
    ctaType: "GET_QUOTE",
    linkUrl: "https://detroitwebagent.com/start-here?product=contractor_leads&utm_source=meta&utm_medium=paid&utm_campaign=contractor_leads_factory",
    bodyTemplate: "Your competitors are paying for the same Angi leads you are. Exclusive contractor leads in your territory — nobody else gets them. $399/mo.",
    thumbnailUrl: "https://www.detroitwebagent.com/dwa-og-image.png",
  },
  gng: {
    campaignPrefix: "Guilds and Grains",
    defaultPageId: "1110608005476128",
    // instagramActorId: TBD — create @guildsandgrains IG account and link to FB page in Business Manager
    objective: "OUTCOME_SALES",
    ctaType: "SHOP_NOW",
    linkUrl: "https://www.etsy.com/shop/GuildsAndGrains",
    bodyTemplate: "Unique handcrafted & print-on-demand gifts. Shop Guilds and Grains on Etsy — fast shipping, great quality.",
  },
};

// ── Main handler ──────────────────────────────────────────────────────────────
serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: cors });

  const TOKEN = Deno.env.get("META_USER_ACCESS_TOKEN") ?? "";
  const AD_ACCOUNT = Deno.env.get("META_AD_ACCOUNT_ID") ?? "act_1969872620513768";
  const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
  const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

  const json = (data: unknown, status = 200) =>
    new Response(JSON.stringify(data), { status, headers: { ...cors, "Content-Type": "application/json" } });

  const sb = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false } });

  let body: Record<string, unknown> = {};
  try { body = await req.json(); } catch { /* GET or empty body ok */ }

  // ── Mode: listPages — show all FB pages this token can access ───────────────
  if (body.listPages === true) {
    if (!TOKEN) return json({ error: "META_USER_ACCESS_TOKEN not set" }, 400);
    const pagesRes = await fetch(`${META}/me/accounts?fields=id,name,category&limit=25&access_token=${TOKEN}`);
    const pagesData = await pagesRes.json();
    return json({ pages: pagesData.data ?? [], error: pagesData.error?.message ?? null });
  }

  // ── Mode: campaignStats — return status + insights for a brand's campaign ────
  // POST {"campaignStats":"dwa"} — returns spend/impressions/clicks/CTR + campaign status
  if (body.campaignStats) {
    if (!TOKEN) return json({ error: "META_USER_ACCESS_TOKEN not set" }, 400);
    const brandSlug = body.campaignStats as string;
    // Known campaign IDs by brand (created via this function)
    const CAMPAIGN_IDS: Record<string, string> = {
      dwa: "120243880723670377",
    };
    const campaignId = CAMPAIGN_IDS[brandSlug];
    if (!campaignId) return json({ error: `No campaign ID on file for brand: ${brandSlug}` }, 400);

    const [statusRes, insightRes, adSetRes] = await Promise.all([
      fetch(`${META}/${campaignId}?fields=name,status,daily_budget,created_time,objective&access_token=${TOKEN}`),
      fetch(`${META}/${campaignId}/insights?fields=spend,impressions,clicks,ctr,actions&date_preset=last_30d&access_token=${TOKEN}`),
      fetch(`${META}/${campaignId}/adsets?fields=name,status,daily_budget,targeting&access_token=${TOKEN}`),
    ]);
    const [statusData, insightData, adSetData] = await Promise.all([
      statusRes.json(), insightRes.json(), adSetRes.json(),
    ]);

    return json({
      campaignId,
      campaign: statusData,
      insights: insightData?.data?.[0] ?? null,
      adSets: adSetData?.data ?? [],
    });
  }

  // ── Mode: toggleCampaignStatus — activate or pause a campaign ────────────────
  // POST {"toggleCampaignStatus":"dwa","newStatus":"ACTIVE"} or "PAUSED"
  if (body.toggleCampaignStatus) {
    if (!TOKEN) return json({ error: "META_USER_ACCESS_TOKEN not set" }, 400);
    const brandSlug = body.toggleCampaignStatus as string;
    const newStatus = (body.newStatus as string)?.toUpperCase();
    if (!["ACTIVE", "PAUSED"].includes(newStatus)) {
      return json({ error: "newStatus must be ACTIVE or PAUSED" }, 400);
    }
    const CAMPAIGN_IDS: Record<string, string> = {
      dwa: "120243880723670377",
    };
    const campaignId = CAMPAIGN_IDS[brandSlug];
    if (!campaignId) return json({ error: `No campaign ID on file for brand: ${brandSlug}` }, 400);

    const toggleRes = await fetch(`${META}/${campaignId}`, {
      method: "POST",
      headers: { "Authorization": `Bearer ${TOKEN}`, "Content-Type": "application/json" },
      body: JSON.stringify({ status: newStatus }),
    });
    const toggleData = await toggleRes.json();
    if (toggleData.error) throw new Error(`Toggle failed: ${JSON.stringify(toggleData.error)}`);
    log("Campaign status toggled", { campaignId, newStatus });
    return json({ success: true, campaignId, newStatus });
  }

  // ── Mode: videoUrl — create a Meta VIDEO ad from a pre-rendered video URL ───
  // POST {"videoUrl":"https://...mp4","brandSlug":"dwa","dailyBudgetCents":500}
  if (body.videoUrl) {
    const videoUrl = body.videoUrl as string;
    const brandSlugV = (body.brandSlug as string) ?? "dwa";
    const budgetV = (body.dailyBudgetCents as number) ?? 500;

    if (!TOKEN) return json({ error: "META_USER_ACCESS_TOKEN not set" }, 400);

    const brand = BRAND_CONFIG[brandSlugV] ?? BRAND_CONFIG.dwa;
    const resolvedPageId = (body.pageId as string) || brand.defaultPageId;
    if (!resolvedPageId) return json({ error: `pageId required for ${brandSlugV}` }, 400);

    const campaignName = `${brand.campaignPrefix} — Video Ad — ${new Date().toISOString().slice(0, 10)}`;
    const headline = brand.campaignPrefix.slice(0, 40);
    const bodyText = brand.bodyTemplate.slice(0, 125);

    log("Starting Meta VIDEO ad post", { videoUrl: videoUrl.slice(0, 80), brandSlugV, budgetV });

    try {
      const videoId = await uploadVideoToMeta(videoUrl, campaignName, AD_ACCOUNT, TOKEN);
      const campaignId = await createCampaign(AD_ACCOUNT, campaignName, brand.objective, TOKEN);
      const adSetId = await createAdSet(
        AD_ACCOUNT, campaignId, `${campaignName} — US 25-55`,
        budgetV, brand.objective, TOKEN, brand.instagramActorId
      );
      const creativeId = await createVideoAdCreative(
        AD_ACCOUNT, resolvedPageId, videoId, headline, bodyText,
        brand.linkUrl, brand.ctaType, `${campaignName} — Creative`, TOKEN, brand.instagramActorId, brand.thumbnailUrl
      );
      const adId = await createAd(AD_ACCOUNT, adSetId, creativeId, campaignName, TOKEN);
      const adsManagerUrl = `https://www.facebook.com/adsmanager/manage/ads?act=${AD_ACCOUNT.replace("act_", "")}&selected_campaign_ids=${campaignId}`;

      const { error: saveErr } = await sb.from("meta_ad_campaigns").upsert({
        job_id: null,
        campaign_id: campaignId,
        adset_id: adSetId,
        creative_id: creativeId,
        ad_id: adId,
        page_id: resolvedPageId,
        brand_slug: brandSlugV,
        campaign_name: campaignName,
        status: "PAUSED",
        daily_budget_cents: budgetV,
        ads_manager_url: adsManagerUrl,
        image_url: videoUrl,
        created_at: new Date().toISOString(),
      }, { onConflict: "campaign_id", ignoreDuplicates: false });
      if (saveErr) log("DB save warning (non-fatal)", { err: saveErr.message });

      return json({
        success: true, campaignId, adSetId, creativeId, adId, videoId,
        status: "PAUSED",
        adsManagerUrl,
        note: "Video campaign is PAUSED — go to Ads Manager to review + activate",
        placements: brand.instagramActorId ? "Facebook Feed + Instagram Feed + Reels" : "Facebook Feed",
        dailyBudgetUsd: budgetV / 100,
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log("Video ad error", { error: msg });
      return json({ error: msg }, 500);
    }
  }

  // ── Validate required params ───────────────────────────────────────────────
  const { jobId, pageId, brandSlug = "m2", dailyBudgetCents = 500, dryRun = false, linkUrl: linkUrlOverride } = body as {
    jobId?: string;
    pageId?: string;
    brandSlug?: string;
    dailyBudgetCents?: number;
    dryRun?: boolean;
    linkUrl?: string; // optional override for landing URL (adds UTM per-campaign)
  };

  if (!jobId) return json({ error: "jobId required — get from ad_studio_jobs table" }, 400);
  if (!TOKEN) return json({ error: "META_USER_ACCESS_TOKEN not set in Supabase secrets" }, 400);

  const brand = BRAND_CONFIG[brandSlug as string] ?? BRAND_CONFIG.m2;
  // Allow per-call linkUrl override so callers can pass campaign-specific UTM URLs
  if (linkUrlOverride) brand.linkUrl = linkUrlOverride;
  const resolvedPageId = (pageId as string) || brand.defaultPageId;
  if (!resolvedPageId) return json({ error: `pageId required for ${brandSlug} — no default set yet. Call {listPages:true} to find yours.` }, 400);

  try {
    // ── Fetch the ad creative job ─────────────────────────────────────────────
    const { data: job, error: jobErr } = await sb
      .from("ad_studio_jobs")
      .select("*")
      .eq("id", jobId)
      .single();

    if (jobErr || !job) return json({ error: `Job not found: ${jobErr?.message}` }, 404);

    const j = job as {
      id: string;
      product: string;
      concept_name: string;
      niche: string;
      format_urls: Record<string, string>; // {meta_feed: url, meta_story: url, meta_link: url}
      headline?: string;
      subhead?: string;
    };

    // Pick the best image: meta_link (1.91:1) for feed ads, meta_feed (1:1) as fallback
    const imageUrl = j.format_urls?.meta_link ?? j.format_urls?.meta_feed ?? Object.values(j.format_urls ?? {})[0];
    if (!imageUrl) return json({ error: "No image URL in job — run ad-creative-studio first" }, 400);

    const campaignName = `${brand.campaignPrefix} — ${j.concept_name ?? j.niche} — ${new Date().toISOString().slice(0, 10)}`;
    const headline = (j.headline ?? `${j.concept_name} — ${j.niche}`).slice(0, 40);
    const bodyText = (j.subhead ?? brand.bodyTemplate).slice(0, 125);

    log("Starting Meta ad post", {
      jobId,
      campaign: campaignName,
      imageUrl: imageUrl.slice(0, 80),
      pageId: resolvedPageId,
      brandSlug,
      dailyBudgetCents,
      dryRun,
    });

    if (dryRun) {
      return json({
        dryRun: true,
        plan: {
          campaign: campaignName,
          objective: brand.objective,
          pageId: resolvedPageId,
          adAccount: AD_ACCOUNT,
          imageUrl,
          headline,
          bodyText: bodyText.slice(0, 60) + "...",
          ctaType: brand.ctaType,
          linkUrl: brand.linkUrl,
          dailyBudgetUsd: dailyBudgetCents / 100,
          placements: brand.instagramActorId ? "Facebook Feed + Instagram Feed + Reels" : "Facebook Feed only",
          instagramActorId: brand.instagramActorId ?? null,
          status: "PAUSED (activate in Ads Manager after review)",
        },
        nextStep: "Remove dryRun:true to create the campaign",
      });
    }

    // ── Step 1: Upload image ──────────────────────────────────────────────────
    const imageHash = await uploadImageToMeta(
      imageUrl,
      `${j.slug ?? j.niche}_${j.concept ?? "ad"}_${Date.now()}.jpg`,
      AD_ACCOUNT,
      TOKEN
    );

    // ── Step 2: Create Campaign ───────────────────────────────────────────────
    const campaignId = await createCampaign(AD_ACCOUNT, campaignName, brand.objective, TOKEN);

    // ── Step 3: Create Ad Set ─────────────────────────────────────────────────
    const adSetId = await createAdSet(
      AD_ACCOUNT,
      campaignId,
      `${campaignName} — US 25-55`,
      dailyBudgetCents,
      brand.objective,
      TOKEN,
      brand.instagramActorId
    );

    // ── Step 4: Create Creative ───────────────────────────────────────────────
    const creativeId = await createAdCreative(
      AD_ACCOUNT,
      resolvedPageId,
      imageHash,
      headline,
      bodyText,
      brand.linkUrl,
      brand.ctaType,
      `${campaignName} — Creative`,
      TOKEN,
      brand.instagramActorId
    );

    // ── Step 5: Create Ad (PAUSED) ────────────────────────────────────────────
    const adId = await createAd(AD_ACCOUNT, adSetId, creativeId, campaignName, TOKEN);

    const adsManagerUrl = `https://www.facebook.com/adsmanager/manage/ads?act=${AD_ACCOUNT.replace("act_", "")}&selected_campaign_ids=${campaignId}`;

    log("Done", { campaignId, adSetId, creativeId, adId });

    // ── Save to DB ────────────────────────────────────────────────────────────
    const { error: saveErr } = await sb.from("meta_ad_campaigns").upsert({
      job_id: jobId,
      campaign_id: campaignId,
      adset_id: adSetId,
      creative_id: creativeId,
      ad_id: adId,
      page_id: resolvedPageId,
      brand_slug: brandSlug,
      campaign_name: campaignName,
      status: "PAUSED",
      daily_budget_cents: dailyBudgetCents,
      ads_manager_url: adsManagerUrl,
      image_url: imageUrl,
      created_at: new Date().toISOString(),
    }, { onConflict: "campaign_id", ignoreDuplicates: false });

    if (saveErr) log("DB save warning (non-fatal)", { err: saveErr.message });

    return json({
      success: true,
      campaignId,
      adSetId,
      creativeId,
      adId,
      status: "PAUSED",
      adsManagerUrl,
      note: "Campaign is PAUSED — go to Ads Manager to review + activate",
      imageUploaded: imageUrl,
      dailyBudgetUsd: dailyBudgetCents / 100,
    });

  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    log("Error", { error: msg });
    return json({ error: msg }, 500);
  }
});
