import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL") ?? "", Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "");
    const { data: clients } = await supabase.from("review_response_clients").select("*").eq("active", true).limit(50);

    if (!clients?.length) {
      return new Response(JSON.stringify({ message: "No active review response clients" }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY");
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    const FIRECRAWL_API_KEY = Deno.env.get("FIRECRAWL_API_KEY");
    let processed = 0;

    for (const client of clients) {
      try {
        let reviewContext = "";
        if (FIRECRAWL_API_KEY) {
          const searchRes = await fetch("https://api.firecrawl.dev/v1/search", {
            method: "POST",
            headers: { Authorization: `Bearer ${FIRECRAWL_API_KEY}`, "Content-Type": "application/json" },
            body: JSON.stringify({
              query: `"${client.business_name}" reviews Google Yelp`,
              limit: 10,
              scrapeOptions: { formats: ["markdown"] },
            }),
          });
          const searchData = await searchRes.json();
          if (searchData?.data) {
            reviewContext = searchData.data.map((r: any) => r.markdown || r.description || "").join("\n\n").slice(0, 5000);
          }
        }

        const aiRes = await fetch("https://api.anthropic.com/v1/messages", {
          method: "POST",
          headers: { "x-api-key": ANTHROPIC_API_KEY!, "content-type": "application/json", "anthropic-version": "2023-06-01" },
          body: JSON.stringify({
            model: "claude-haiku-4-5-20251001",
            max_tokens: 1200,
            messages: [{
              role: "user",
              content: `You are a review response specialist for ${client.business_name} (${client.industry || "local business"}). 
Brand voice: ${client.brand_voice || "Professional, friendly, grateful for feedback, solution-oriented for complaints."}

Based on recent reviews found online:
${reviewContext || "No specific reviews found. Generate sample response templates instead."}

Generate a daily review response digest as HTML email:
1. For each review found, draft a personalized response (positive reviews: thank + mention specific praise; negative reviews: empathize + offer resolution + take offline)
2. Include the original review snippet and your drafted response
3. Add response tips section
4. Include a "copy & paste" format for easy posting

Dark-themed professional HTML.`,
            }],
          }),
        });

        const aiData = await aiRes.json();
        const responseDigest = aiData?.content?.[0]?.text || "Unable to generate review responses.";

        await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            from: "M² Development <matt@notify.m2training.com>",
            to: [client.email],
            subject: `${client.business_name} — Review Response Drafts Ready`,
            html: `<div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;background:#1a1a2e;color:#e0e0e0;padding:32px;border-radius:12px;">
              <h1 style="color:#e8621a;text-align:center;">Review Response Drafts</h1>
              <p style="color:#888;text-align:center;font-size:13px;">${new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}</p>
              ${responseDigest}
              <hr style="border-color:#333;margin:24px 0;">
              <p style="font-size:11px;color:#666;text-align:center;">Generated by M² Development AI Review Response Service</p>
            </div>`,
          }),
        });

        await supabase.from("review_response_clients").update({ last_sent_at: new Date().toISOString(), send_count: (client.send_count || 0) + 1 }).eq("id", client.id);
        processed++;
      } catch (err) {
        console.error(`Error processing review response client ${client.id}:`, err);
      }
    }

    return new Response(JSON.stringify({ success: true, processed }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) {
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Failed" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
