-- Add product_type to etsy_pod_trends for proper type-level analytics
ALTER TABLE etsy_pod_trends ADD COLUMN IF NOT EXISTS product_type text;

-- Add product_type to pod_niche_library so scanner knows what type each query targets
ALTER TABLE pod_niche_library ADD COLUMN IF NOT EXISTS product_type text;

-- Seed the full 250-niche library (all product types)
-- ON CONFLICT: skip existing rows to preserve scan history
INSERT INTO pod_niche_library (niche, product_type, active, source) VALUES

-- MUG (30)
('funny nurse mug', 'mug', true, 'seed_v2'),
('retirement gift mug', 'mug', true, 'seed_v2'),
('sarcastic mug funny', 'mug', true, 'seed_v2'),
('engineer gift mug', 'mug', true, 'seed_v2'),
('dog dad mug funny', 'mug', true, 'seed_v2'),
('teacher mug gift', 'mug', true, 'seed_v2'),
('funny dad mug', 'mug', true, 'seed_v2'),
('best dad ever mug', 'mug', true, 'seed_v2'),
('cat mom mug funny', 'mug', true, 'seed_v2'),
('wine lover mug funny', 'mug', true, 'seed_v2'),
('plant lady mug funny', 'mug', true, 'seed_v2'),
('fishing dad mug', 'mug', true, 'seed_v2'),
('birthday mug funny gift', 'mug', true, 'seed_v2'),
('sister mug funny gift', 'mug', true, 'seed_v2'),
('best mom ever mug', 'mug', true, 'seed_v2'),
('coworker mug funny gift', 'mug', true, 'seed_v2'),
('witch mug halloween funny', 'mug', true, 'seed_v2'),
('introvert mug funny', 'mug', true, 'seed_v2'),
('anxiety mug funny mental health', 'mug', true, 'seed_v2'),
('book lover mug funny', 'mug', true, 'seed_v2'),
('accountant mug funny gift', 'mug', true, 'seed_v2'),
('firefighter mug gift', 'mug', true, 'seed_v2'),
('police officer mug gift', 'mug', true, 'seed_v2'),
('social worker mug funny', 'mug', true, 'seed_v2'),
('therapist mug funny gift', 'mug', true, 'seed_v2'),
('pharmacist mug gift', 'mug', true, 'seed_v2'),
('veterinarian mug gift', 'mug', true, 'seed_v2'),
('real estate agent mug gift', 'mug', true, 'seed_v2'),
('golf mug funny gift', 'mug', true, 'seed_v2'),
('gym mug fitness funny', 'mug', true, 'seed_v2'),

-- TSHIRT (30)
('nurse life shirt', 'tshirt', true, 'seed_v2'),
('dog mom shirt funny', 'tshirt', true, 'seed_v2'),
('cat lover shirt funny', 'tshirt', true, 'seed_v2'),
('teacher shirt funny', 'tshirt', true, 'seed_v2'),
('nurse shirt funny retro', 'tshirt', true, 'seed_v2'),
('plant mom shirt funny', 'tshirt', true, 'seed_v2'),
('dog dad shirt funny', 'tshirt', true, 'seed_v2'),
('beer lover shirt funny', 'tshirt', true, 'seed_v2'),
('camping shirt funny', 'tshirt', true, 'seed_v2'),
('fishing shirt funny dad', 'tshirt', true, 'seed_v2'),
('hiking shirt funny', 'tshirt', true, 'seed_v2'),
('wine mom shirt funny', 'tshirt', true, 'seed_v2'),
('gym workout shirt funny', 'tshirt', true, 'seed_v2'),
('sarcastic funny shirt women', 'tshirt', true, 'seed_v2'),
('mom life shirt funny', 'tshirt', true, 'seed_v2'),
('grandma shirt funny gift', 'tshirt', true, 'seed_v2'),
('halloween funny shirt women', 'tshirt', true, 'seed_v2'),
('christmas funny shirt family', 'tshirt', true, 'seed_v2'),
('retirement funny shirt', 'tshirt', true, 'seed_v2'),
('birthday squad shirt funny', 'tshirt', true, 'seed_v2'),
('bachelorette party shirt funny', 'tshirt', true, 'seed_v2'),
('bride shirt bachelorette', 'tshirt', true, 'seed_v2'),
('matching couple shirt funny', 'tshirt', true, 'seed_v2'),
('vet tech shirt funny', 'tshirt', true, 'seed_v2'),
('accountant shirt funny', 'tshirt', true, 'seed_v2'),
('librarian shirt funny', 'tshirt', true, 'seed_v2'),
('social worker shirt funny', 'tshirt', true, 'seed_v2'),
('paramedic emt shirt', 'tshirt', true, 'seed_v2'),
('electrician funny shirt', 'tshirt', true, 'seed_v2'),
('plumber funny shirt', 'tshirt', true, 'seed_v2'),

-- SOCK (20)
('funny novelty crew socks gift', 'sock', true, 'seed_v2'),
('funny food socks men gift', 'sock', true, 'seed_v2'),
('cute animal socks women gift', 'sock', true, 'seed_v2'),
('funny cat socks gift', 'sock', true, 'seed_v2'),
('funny dog socks gift', 'sock', true, 'seed_v2'),
('funny christmas socks stocking', 'sock', true, 'seed_v2'),
('funny avocado socks gift', 'sock', true, 'seed_v2'),
('funny sloth socks gift', 'sock', true, 'seed_v2'),
('funny pizza socks gift', 'sock', true, 'seed_v2'),
('funny taco socks gift', 'sock', true, 'seed_v2'),
('funny unicorn socks women', 'sock', true, 'seed_v2'),
('funny grumpy face socks', 'sock', true, 'seed_v2'),
('funny nurse socks gift', 'sock', true, 'seed_v2'),
('funny teacher socks gift', 'sock', true, 'seed_v2'),
('funny retirement socks gift', 'sock', true, 'seed_v2'),
('funny birthday socks gift', 'sock', true, 'seed_v2'),
('funny dad socks gift', 'sock', true, 'seed_v2'),
('funny beer socks gift men', 'sock', true, 'seed_v2'),
('funny wine socks gift women', 'sock', true, 'seed_v2'),
('funny fishing socks dad', 'sock', true, 'seed_v2'),

-- TUMBLER (20)
('personalized tumbler gift women', 'tumbler', true, 'seed_v2'),
('funny tumbler gift teacher', 'tumbler', true, 'seed_v2'),
('funny tumbler gift nurse', 'tumbler', true, 'seed_v2'),
('funny tumbler gift mom', 'tumbler', true, 'seed_v2'),
('personalized stanley tumbler gift', 'tumbler', true, 'seed_v2'),
('funny tumbler gift coworker', 'tumbler', true, 'seed_v2'),
('funny tumbler gift dog mom', 'tumbler', true, 'seed_v2'),
('funny tumbler gift cat mom', 'tumbler', true, 'seed_v2'),
('funny tumbler gift retirement', 'tumbler', true, 'seed_v2'),
('funny tumbler gift best friend', 'tumbler', true, 'seed_v2'),
('funny tumbler gift sister', 'tumbler', true, 'seed_v2'),
('funny tumbler gift bride', 'tumbler', true, 'seed_v2'),
('tumbler gift bachelorette party', 'tumbler', true, 'seed_v2'),
('funny tumbler gift wine lover', 'tumbler', true, 'seed_v2'),
('funny tumbler gym fitness gift', 'tumbler', true, 'seed_v2'),
('funny tumbler gift birthday', 'tumbler', true, 'seed_v2'),
('funny tumbler gift book lover', 'tumbler', true, 'seed_v2'),
('tumbler gift christmas funny', 'tumbler', true, 'seed_v2'),
('funny 40oz tumbler gift', 'tumbler', true, 'seed_v2'),
('tumbler gift accountant funny', 'tumbler', true, 'seed_v2'),

-- CANDLE (20)
('funny swear word soy candle gift', 'candle', true, 'seed_v2'),
('funny scented candle gift friend', 'candle', true, 'seed_v2'),
('funny candle gift mom', 'candle', true, 'seed_v2'),
('funny candle gift coworker office', 'candle', true, 'seed_v2'),
('funny sarcastic candle birthday', 'candle', true, 'seed_v2'),
('funny candle gift sister', 'candle', true, 'seed_v2'),
('funny candle gift dog mom', 'candle', true, 'seed_v2'),
('funny candle gift nurse', 'candle', true, 'seed_v2'),
('funny candle gift teacher', 'candle', true, 'seed_v2'),
('funny candle gift retirement', 'candle', true, 'seed_v2'),
('funny candle gift best friend', 'candle', true, 'seed_v2'),
('funny candle gift cat lady', 'candle', true, 'seed_v2'),
('funny candle gift wine lover', 'candle', true, 'seed_v2'),
('funny anxiety candle gift', 'candle', true, 'seed_v2'),
('funny witchy candle halloween', 'candle', true, 'seed_v2'),
('funny candle gift introvert', 'candle', true, 'seed_v2'),
('funny candle gift bookworm', 'candle', true, 'seed_v2'),
('funny candle gift wedding', 'candle', true, 'seed_v2'),
('funny birthday candle gift', 'candle', true, 'seed_v2'),
('funny candle gift therapist', 'candle', true, 'seed_v2'),

-- HOODIE (15)
('funny hoodie gift women', 'hoodie', true, 'seed_v2'),
('nurse hoodie gift', 'hoodie', true, 'seed_v2'),
('teacher hoodie gift', 'hoodie', true, 'seed_v2'),
('dog mom hoodie funny', 'hoodie', true, 'seed_v2'),
('cat mom hoodie funny', 'hoodie', true, 'seed_v2'),
('funny retirement hoodie gift', 'hoodie', true, 'seed_v2'),
('funny mom life hoodie', 'hoodie', true, 'seed_v2'),
('funny halloween hoodie women', 'hoodie', true, 'seed_v2'),
('funny christmas hoodie family', 'hoodie', true, 'seed_v2'),
('wine lover hoodie funny', 'hoodie', true, 'seed_v2'),
('camping hoodie funny', 'hoodie', true, 'seed_v2'),
('hiking hoodie funny', 'hoodie', true, 'seed_v2'),
('sarcastic hoodie funny women', 'hoodie', true, 'seed_v2'),
('funny gaming hoodie gift', 'hoodie', true, 'seed_v2'),
('gym hoodie funny', 'hoodie', true, 'seed_v2'),

-- SWEATSHIRT (10)
('funny sweatshirt women gift', 'sweatshirt', true, 'seed_v2'),
('funny crewneck sweatshirt gift', 'sweatshirt', true, 'seed_v2'),
('nurse sweatshirt gift', 'sweatshirt', true, 'seed_v2'),
('teacher sweatshirt gift', 'sweatshirt', true, 'seed_v2'),
('dog mom sweatshirt funny', 'sweatshirt', true, 'seed_v2'),
('cat mom sweatshirt funny', 'sweatshirt', true, 'seed_v2'),
('christmas sweatshirt funny women', 'sweatshirt', true, 'seed_v2'),
('halloween sweatshirt funny women', 'sweatshirt', true, 'seed_v2'),
('sarcastic sweatshirt women', 'sweatshirt', true, 'seed_v2'),
('vintage retro sweatshirt funny', 'sweatshirt', true, 'seed_v2'),

-- HAT (15)
('funny dad hat gift', 'hat', true, 'seed_v2'),
('funny trucker hat gift men', 'hat', true, 'seed_v2'),
('funny baseball cap gift', 'hat', true, 'seed_v2'),
('cat mom hat funny', 'hat', true, 'seed_v2'),
('dog dad hat funny', 'hat', true, 'seed_v2'),
('fishing hat funny dad', 'hat', true, 'seed_v2'),
('golf hat funny', 'hat', true, 'seed_v2'),
('camping hat funny', 'hat', true, 'seed_v2'),
('retirement hat funny gift', 'hat', true, 'seed_v2'),
('nurse hat funny gift', 'hat', true, 'seed_v2'),
('teacher hat funny gift', 'hat', true, 'seed_v2'),
('bachelorette hat funny', 'hat', true, 'seed_v2'),
('birthday hat funny gift', 'hat', true, 'seed_v2'),
('mom hat funny gift', 'hat', true, 'seed_v2'),
('wine lover hat funny', 'hat', true, 'seed_v2'),

-- PILLOW (15)
('funny throw pillow gift', 'pillow', true, 'seed_v2'),
('funny couch pillow sarcastic', 'pillow', true, 'seed_v2'),
('funny cat pillow gift', 'pillow', true, 'seed_v2'),
('funny dog pillow gift', 'pillow', true, 'seed_v2'),
('funny napping pillow gift', 'pillow', true, 'seed_v2'),
('funny retirement pillow gift', 'pillow', true, 'seed_v2'),
('funny mom pillow gift', 'pillow', true, 'seed_v2'),
('funny couples pillow gift', 'pillow', true, 'seed_v2'),
('funny home decor pillow', 'pillow', true, 'seed_v2'),
('funny birthday pillow gift', 'pillow', true, 'seed_v2'),
('boho throw pillow home decor', 'pillow', true, 'seed_v2'),
('floral pillow home decor gift', 'pillow', true, 'seed_v2'),
('funny office pillow gift', 'pillow', true, 'seed_v2'),
('personalized pillow gift', 'pillow', true, 'seed_v2'),
('funny wine lover pillow', 'pillow', true, 'seed_v2'),

-- STICKER (10)
('funny laptop sticker pack', 'sticker', true, 'seed_v2'),
('funny water bottle sticker', 'sticker', true, 'seed_v2'),
('funny cat sticker', 'sticker', true, 'seed_v2'),
('funny dog sticker', 'sticker', true, 'seed_v2'),
('sarcastic funny sticker', 'sticker', true, 'seed_v2'),
('funny nurse sticker', 'sticker', true, 'seed_v2'),
('mental health funny sticker', 'sticker', true, 'seed_v2'),
('funny book lover sticker', 'sticker', true, 'seed_v2'),
('funny plant sticker', 'sticker', true, 'seed_v2'),
('funny food sticker pack', 'sticker', true, 'seed_v2'),

-- POSTER / WALL ART (10)
('funny bathroom wall art print', 'poster_v', true, 'seed_v2'),
('funny kitchen wall art print', 'poster_v', true, 'seed_v2'),
('funny office wall art print', 'poster_v', true, 'seed_v2'),
('motivational funny wall art', 'poster_v', true, 'seed_v2'),
('funny bedroom wall art teen', 'poster_v', true, 'seed_v2'),
('boho floral wall art print', 'poster_v', true, 'seed_v2'),
('minimalist wall art home decor', 'poster_v', true, 'seed_v2'),
('funny laundry room sign', 'poster_h', true, 'seed_v2'),
('funny dog wall art print', 'poster_h', true, 'seed_v2'),
('funny cat wall art print', 'poster_h', true, 'seed_v2'),

-- BLANKET (10)
('funny sherpa blanket gift', 'blanket', true, 'seed_v2'),
('personalized blanket gift', 'blanket', true, 'seed_v2'),
('funny retirement blanket gift', 'blanket', true, 'seed_v2'),
('funny cat blanket gift', 'blanket', true, 'seed_v2'),
('funny dog blanket gift', 'blanket', true, 'seed_v2'),
('funny birthday blanket gift', 'blanket', true, 'seed_v2'),
('funny mom blanket gift', 'blanket', true, 'seed_v2'),
('funny couch potato blanket', 'blanket', true, 'seed_v2'),
('christmas blanket gift funny', 'blanket', true, 'seed_v2'),
('funny nurse blanket gift', 'blanket', true, 'seed_v2'),

-- APRON (10)
('funny kitchen apron gift', 'apron', true, 'seed_v2'),
('funny bbq grill apron dad', 'apron', true, 'seed_v2'),
('funny baking apron women', 'apron', true, 'seed_v2'),
('funny bartender apron gift', 'apron', true, 'seed_v2'),
('personalized apron gift', 'apron', true, 'seed_v2'),
('funny dog mom apron', 'apron', true, 'seed_v2'),
('funny retirement apron gift', 'apron', true, 'seed_v2'),
('funny cat lady apron', 'apron', true, 'seed_v2'),
('funny grill master apron', 'apron', true, 'seed_v2'),
('funny wine lover apron', 'apron', true, 'seed_v2'),

-- ORNAMENT (10)
('funny christmas ornament gift', 'ornament', true, 'seed_v2'),
('funny dog ornament christmas', 'ornament', true, 'seed_v2'),
('funny cat ornament christmas', 'ornament', true, 'seed_v2'),
('personalized christmas ornament', 'ornament', true, 'seed_v2'),
('funny family ornament gift', 'ornament', true, 'seed_v2'),
('funny nurse ornament christmas', 'ornament', true, 'seed_v2'),
('funny teacher ornament christmas', 'ornament', true, 'seed_v2'),
('funny retirement ornament', 'ornament', true, 'seed_v2'),
('funny couples ornament', 'ornament', true, 'seed_v2'),
('funny baby first christmas ornament', 'ornament', true, 'seed_v2'),

-- JOURNAL (10)
('funny journal notebook gift', 'journal', true, 'seed_v2'),
('funny nurse notebook gift', 'journal', true, 'seed_v2'),
('funny teacher notebook gift', 'journal', true, 'seed_v2'),
('funny anxiety journal gift', 'journal', true, 'seed_v2'),
('funny sarcastic journal women', 'journal', true, 'seed_v2'),
('funny cat mom journal', 'journal', true, 'seed_v2'),
('funny dog mom journal', 'journal', true, 'seed_v2'),
('personalized journal gift', 'journal', true, 'seed_v2'),
('funny retirement journal', 'journal', true, 'seed_v2'),
('funny wine lover journal', 'journal', true, 'seed_v2'),

-- DIGITAL (10)
('printable wall art funny instant download', 'digital', true, 'seed_v2'),
('printable birthday card funny download', 'digital', true, 'seed_v2'),
('printable planner funny download', 'digital', true, 'seed_v2'),
('svg bundle funny quotes commercial use', 'digital', true, 'seed_v2'),
('svg nurse cut file bundle', 'digital', true, 'seed_v2'),
('svg teacher cut file bundle', 'digital', true, 'seed_v2'),
('printable gift tag funny download', 'digital', true, 'seed_v2'),
('printable baby shower game download', 'digital', true, 'seed_v2'),
('svg funny mom quotes bundle', 'digital', true, 'seed_v2'),
('printable coloring pages adults funny', 'digital', true, 'seed_v2')

ON CONFLICT (niche) DO UPDATE SET
  product_type = EXCLUDED.product_type,
  active = true;
