-- Add localized_metadata JSONB to pod_digital_products
-- Stores DE/ES/FR marketplace metadata generated by pod-seo-agent
ALTER TABLE pod_digital_products
  ADD COLUMN IF NOT EXISTS localized_metadata jsonb;
