ALTER TABLE public.outreach_leads
  ADD COLUMN IF NOT EXISTS offer_pitched TEXT,
  ADD COLUMN IF NOT EXISTS sms_sent BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS sms_sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS sms_2_sent BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS sms_2_sent_at TIMESTAMPTZ;