-- LinkedIn Outreach — Monday 7am ET (12:00 UTC)
SELECT cron.schedule('linkedin-outreach-weekly','0 12 * * 1',$$SELECT extensions.http_post(url:='https://eauvubfpanpeuxsrqesu.supabase.co/functions/v1/linkedin-outreach-sender',headers:=jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||(SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name='email_queue_service_role_key' LIMIT 1)),body:='{}'::jsonb) AS request_id;$$);
-- Abandoned Cart — Tuesday 8am ET (13:00 UTC)
SELECT cron.schedule('abandoned-cart-weekly','0 13 * * 2',$$SELECT extensions.http_post(url:='https://eauvubfpanpeuxsrqesu.supabase.co/functions/v1/abandoned-cart-sender',headers:=jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||(SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name='email_queue_service_role_key' LIMIT 1)),body:='{}'::jsonb) AS request_id;$$);
-- Client Report — 1st of month 9am ET (14:00 UTC)
SELECT cron.schedule('client-report-monthly','0 14 1 * *',$$SELECT extensions.http_post(url:='https://eauvubfpanpeuxsrqesu.supabase.co/functions/v1/client-report-sender',headers:=jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||(SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name='email_queue_service_role_key' LIMIT 1)),body:='{}'::jsonb) AS request_id;$$);
-- Restaurant Menu — 15th of month 9am ET (14:00 UTC)
SELECT cron.schedule('restaurant-menu-monthly','0 14 15 * *',$$SELECT extensions.http_post(url:='https://eauvubfpanpeuxsrqesu.supabase.co/functions/v1/restaurant-menu-sender',headers:=jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||(SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name='email_queue_service_role_key' LIMIT 1)),body:='{}'::jsonb) AS request_id;$$);
-- Insurance Drip — Wednesday 9am ET (14:00 UTC)
SELECT cron.schedule('insurance-drip-weekly','0 14 * * 3',$$SELECT extensions.http_post(url:='https://eauvubfpanpeuxsrqesu.supabase.co/functions/v1/insurance-drip-sender',headers:=jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||(SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name='email_queue_service_role_key' LIMIT 1)),body:='{}'::jsonb) AS request_id;$$);
-- Podcast Pitch — 10th of month 9am ET (14:00 UTC)
SELECT cron.schedule('podcast-pitch-monthly','0 14 10 * *',$$SELECT extensions.http_post(url:='https://eauvubfpanpeuxsrqesu.supabase.co/functions/v1/podcast-pitch-sender',headers:=jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||(SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name='email_queue_service_role_key' LIMIT 1)),body:='{}'::jsonb) AS request_id;$$);
-- Testimonial Harvester — Thursday 8am ET (13:00 UTC)
SELECT cron.schedule('testimonial-harvester-weekly','0 13 * * 4',$$SELECT extensions.http_post(url:='https://eauvubfpanpeuxsrqesu.supabase.co/functions/v1/testimonial-harvester-sender',headers:=jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||(SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name='email_queue_service_role_key' LIMIT 1)),body:='{}'::jsonb) AS request_id;$$);
-- New Mover Marketing — Friday 9am ET (14:00 UTC)
SELECT cron.schedule('new-mover-weekly','0 14 * * 5',$$SELECT extensions.http_post(url:='https://eauvubfpanpeuxsrqesu.supabase.co/functions/v1/new-mover-sender',headers:=jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||(SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name='email_queue_service_role_key' LIMIT 1)),body:='{}'::jsonb) AS request_id;$$);
-- Annual Business Review — Jan 5 9am ET (14:00 UTC)
SELECT cron.schedule('annual-review-yearly','0 14 5 1 *',$$SELECT extensions.http_post(url:='https://eauvubfpanpeuxsrqesu.supabase.co/functions/v1/annual-review-sender',headers:=jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||(SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name='email_queue_service_role_key' LIMIT 1)),body:='{}'::jsonb) AS request_id;$$);
