import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL") ?? "", Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "");
    const { data: clients } = await supabase.from("grant_finder_clients").select("*").eq("active", true).limit(50);

    if (!clients?.length) {
      return new Response(JSON.stringify({ message: "No active grant finder clients" }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY") || "";
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    const FIRECRAWL_API_KEY = Deno.env.get("FIRECRAWL_API_KEY");
    let processed = 0;

    for (const client of clients) {
      try {
        let grantContext = "";
        if (FIRECRAWL_API_KEY) {
          const searchRes = await fetch("https://api.firecrawl.dev/v1/search", {
            method: "POST",
            headers: { Authorization: `Bearer ${FIRECRAWL_API_KEY}`, "Content-Type": "application/json" },
            body: JSON.stringify({
              query: `small business grants ${client.industry || ""} ${client.location || "Michigan"} ${new Date().getFullYear()} application deadline`,
              limit: 8,
              scrapeOptions: { formats: ["markdown"] } }) });
          const searchData = await searchRes.json();
          if (searchData?.data) {
            grantContext = searchData.data.map((r: any) => `${r.title || ""}: ${r.markdown || r.description || ""}`).join("\n\n").slice(0, 5000);
          }
        }

        const aiRes = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
          method: "POST",
          headers: { Authorization: `Bearer ${LOVABLE_API_KEY}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            model: "google/gemini-2.5-flash-lite", 
            messages: [{
              role: "user",
              content: `You are a grant research assistant. Find and summarize grant opportunities for ${client.business_name}, a ${client.industry || "small"} business in ${client.location || "Michigan"} with ${client.employee_count || "under 50"} employees and ${client.annual_revenue || "under $5M"} annual revenue.

Grant research data:
${grantContext || "Use general knowledge of current SBA, MEDC, and federal grant programs."}

Format as HTML email with:
1. Top 5 matching grants with: name, amount, deadline, eligibility summary, application link
2. Quick eligibility checklist for each
3. Priority ranking (best match first)
4. Next steps / action items

Professional dark-themed HTML formatting.` }] }) });

        const aiData = await aiRes.json();
        const grantReport = aiData?.choices?.[0]?.message?.content || "Unable to generate grant report.";

        await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            from: "M² Development <matt@notify.m2training.com>",
            to: [client.email],
            subject: `${client.business_name} — Weekly Grant Opportunities`,
            html: `<div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;background:#1a1a2e;color:#e0e0e0;padding:32px;border-radius:12px;">
              <h1 style="color:#e8621a;text-align:center;">Grant Opportunities Report</h1>
              <p style="color:#888;text-align:center;font-size:13px;">${client.business_name} — Week of ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
              ${grantReport}
              <hr style="border-color:#333;margin:24px 0;">
              <p style="font-size:11px;color:#666;text-align:center;">Generated by M² Development AI Grant Finder<br>Reply to discuss any opportunities.</p>
            </div>` }) });

        await supabase.from("grant_finder_clients").update({ last_sent_at: new Date().toISOString(), send_count: (client.send_count || 0) + 1 }).eq("id", client.id);
        processed++;
      } catch (err) {
        console.error(`Error processing grant finder client ${client.id}:`, err);
      }
    }

    return new Response(JSON.stringify({ success: true, processed }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) {
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Failed" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
