import {
  MapPin, TrendingUp, FileSearch,
  MessageSquare, RefreshCw, Phone, Globe,
  type LucideIcon,
} from "lucide-react";

export interface AddOn {
  key: string;
  icon: LucideIcon;
  name: string;
  price: string;
  priceSub: string;
  priceCents: number;
  color: string;
  desc: string;
  includes: string[];
  recurring: boolean;
  price_id: string;
  product_id: string;
}

export const ADD_ONS: AddOn[] = [
  {
    key: "review_response",
    icon: MessageSquare,
    name: "AI Review Response Service",
    price: "$49/mo",
    priceSub: "ongoing service",
    priceCents: 4900,
    color: "#0891b2",
    desc: "I monitor your Google and Yelp reviews and write professional responses within 24 hours — good or bad.",
    includes: [
      "Monitor Google, Yelp & Facebook reviews",
      "Professional responses within 24 hours",
      "Monthly reputation summary report",
      "Strategy for generating more 5-star reviews",
      "Negative review escalation handling",
    ],
    recurring: true,
    price_id: "price_1THIOhD52tPWee46DlPYS7KZ",
    product_id: "prod_UFo0Bgx4iwu7lP",
  },
  {
    key: "missed_call",
    icon: Phone,
    name: "Missed-Call Text-Back",
    price: "$99/mo",
    priceSub: "never lose a lead",
    priceCents: 9900,
    color: "#e8621a",
    desc: "When someone calls and you can't answer, our system instantly texts them back — capturing the lead before they call your competitor.",
    includes: [
      "Instant SMS auto-reply on missed calls",
      "Customizable response templates",
      "Lead capture & notification to you",
      "Works with your existing business number",
      "Monthly analytics report",
    ],
    recurring: true,
    price_id: "price_1THIPrD52tPWee46uvbeRKlL",
    product_id: "prod_UFo1TyWkgI3AcF",
  },
  {
    key: "job_posting",
    icon: Globe,
    name: "AI Job Posting Writer",
    price: "$29/mo",
    priceSub: "monthly refreshed listings",
    priceCents: 2900,
    color: "#10b981",
    desc: "AI writes and refreshes your job postings monthly for Indeed, LinkedIn, and other boards — so you always attract the right candidates.",
    includes: [
      "Monthly job listing refresh",
      "Optimized for Indeed & LinkedIn",
      "Industry-specific language",
      "A/B tested titles & descriptions",
      "Delivered via email on the 1st",
    ],
    recurring: true,
    price_id: "price_1THIPVD52tPWee460ZVZoaYp",
    product_id: "prod_UFo1hGS5DM91nR",
  },
  {
    key: "quote_followup",
    icon: MessageSquare,
    name: "AI Quote Follow-Up Sequences",
    price: "$49/mo",
    priceSub: "close more deals",
    priceCents: 4900,
    color: "#f59e0b",
    desc: "When you send a quote, our system auto-sends 3-5 follow-up emails/texts over 14 days to close the deal before they ghost.",
    includes: [
      "Automated 3-5 step follow-up sequence",
      "SMS + email combo for max response",
      "Customizable messaging templates",
      "Timing optimized for conversion",
      "Monthly close-rate report",
    ],
    recurring: true,
    price_id: "price_1THIPnD52tPWee46hK3ma3Iq",
    product_id: "prod_UFo1QFkBVvLuGa",
  },
  {
    key: "competitor_intel",
    icon: FileSearch,
    name: "Weekly Competitor Intel Report",
    price: "$69/mo",
    priceSub: "know what they're doing",
    priceCents: 6900,
    color: "#8b5cf6",
    desc: "AI monitors 3 competitors' websites, reviews, and social media weekly and emails you a plain-English summary of what changed.",
    includes: [
      "Monitor 3 competitors weekly",
      "Website change detection",
      "Review sentiment tracking",
      "Social media activity summary",
      "Delivered every Monday morning",
    ],
    recurring: true,
    price_id: "price_1THIPpD52tPWee469IzqQxa2",
    product_id: "prod_UFo1v0LmlodE1L",
  },
  {
    key: "gbp_management",
    icon: MapPin,
    name: "Google Business Profile Management",
    price: "$49/mo",
    priceSub: "ongoing management",
    priceCents: 4900,
    color: "#059669",
    desc: "Your GBP is often the first thing customers see. I optimize your profile, add weekly posts, and respond to reviews — so you rank higher on Google Maps.",
    includes: [
      "Full profile setup & optimization",
      "4 GBP posts per month",
      "Review response management",
      "Photo uploads & service updates",
      "Monthly ranking check",
    ],
    recurring: true,
    price_id: "price_1THQqkD52tPWee46fvgmrhvG",
    product_id: "prod_UFwkxxErqpyPuZ",
  },
  {
    key: "website_audit",
    icon: FileSearch,
    name: "Website Audit & Report",
    price: "$49",
    priceSub: "one-time · any website",
    priceCents: 4900,
    color: "#dc2626",
    desc: "Not sure why your site isn't converting? I run a full audit — speed, SEO, mobile experience, call-to-action placement — and send you a plain-English report.",
    includes: [
      "Page speed & Core Web Vitals check",
      "SEO & keyword gap analysis",
      "Mobile usability review",
      "Conversion rate issues identified",
      "Prioritized fix list delivered within 48 hrs",
    ],
    recurring: false,
    price_id: "price_1THQr8D52tPWee46lZDu7pDo",
    product_id: "prod_UFwkZzCdjaYmu2",
  },
  {
    key: "website_refresh",
    icon: RefreshCw,
    name: "Website Refresh",
    price: "$199",
    priceSub: "one-time",
    priceCents: 19900,
    color: "#7c3aed",
    desc: "Already have a site but it looks dated? I'll rewrite your homepage copy, update CTAs, fix mobile issues, and modernize the layout.",
    includes: [
      "Full homepage copy rewrite",
      "Updated call-to-action buttons & placement",
      "Mobile responsiveness fixes",
      "Speed optimization pass",
      "1 round of revisions included",
    ],
    recurring: false,
    price_id: "price_1THQr8D52tPWee46lZDu7pDo",
    product_id: "prod_UFwkZzCdjaYmu2",
  },
  {
    key: "local_seo_pages",
    icon: TrendingUp,
    name: "Local SEO Landing Pages",
    price: "$299",
    priceSub: "10-page package · one-time",
    priceCents: 29900,
    color: "#d97706",
    desc: "Get found for 10 local search terms. I build dedicated pages targeting keywords like 'plumber Grosse Pointe' or 'electrician Harper Woods'.",
    includes: [
      "10 keyword-targeted landing pages",
      "Location-specific copy on each page",
      "SEO meta tags & schema markup",
      "Submitted to Google Search Console",
      "Linked from your main site",
    ],
    recurring: false,
    price_id: "price_1THQrCD52tPWee46S22fwipp",
    product_id: "prod_UFwkmd0j46x9Gb",
  },
];

export const getAddonByKey = (key: string) => ADD_ONS.find((a) => a.key === key);
